oscl: OsclJump Class Reference
OsclJump Class Reference
[OSCL Error]
#include <oscl_error_imp_jumps.h>
Public Member Functions
void Jump (int a)
jmp_buf * Top ()
~OsclJump ()
Static Public Member Functions
static OSCL_IMPORT_REF void StaticJump (int a)
Friends
class OsclErrorTrapImp
Constructor & Destructor Documentation
OsclJump::~OsclJump () [inline]
References OSCL_ASSERT.
Member Function Documentation
void OsclJump::Jump (int a) [inline]
References _OSCL_Abort(), OSCL_ASSERT, and Top().
static OSCL_IMPORT_REF void OsclJump::StaticJump (int a) [static]
jmp_buf* OsclJump::Top () [inline]
References OSCL_ASSERT.
Referenced by Jump().
Friends And Related Function Documentation
friend class OsclErrorTrapImp [friend]
The documentation for this class was generated from the following file:
oscl_error_imp_jumps.h
OSCL API
Posting Version: CORE_9.005.1.1