oscl: OsclMemAllocator Class Reference
OsclMemAllocator Class Reference
[OSCL Memory]
#include <oscl_mem.h>
Public Member Functions
OsclAny * allocate (const uint32 n)
void deallocate (OsclAny *p)
Detailed Description
A simple allocator class. Configurable as to whether this goes through the memory manager or not.
Member Function Documentation
OsclAny* OsclMemAllocator::allocate (const uint32 n) [inline, virtual]
This API throws an exception when malloc returns NULL. n must be greater than 0.
Returns:
pointer (or Leave with OsclErrNoMemory)
Implements Oscl_DefAlloc.
References _oscl_malloc(), Oscl_DefAlloc::allocate_fl(), OsclError::LeaveIfNull(), NULL, and oscl_memset().
Referenced by OsclMemAllocDestructDealloc< T >::allocate().
void OsclMemAllocator::deallocate (OsclAny * p) [inline, virtual]
Implements Oscl_DefAlloc.
References OSCL_FREE.
Referenced by OsclMemAllocDestructDealloc< T >::deallocate().
The documentation for this class was generated from the following file:
oscl_mem.h
OSCL API
Posting Version: CORE_9.005.1.1