oscl: OsclTCPSocketI Class Reference
OsclTCPSocketI Class Reference
#include <oscl_tcp_socket.h>
Public Member Functions
virtual ~OsclTCPSocketI ()
TPVSocketEvent ThreadLogoff ()
TPVSocketEvent ThreadLogon (OsclSocketServI *aServ, OsclSocketObserver *aObserver)
int32 Close ()
int32 Listen (int aQueueSize)
OsclTCPSocketI * GetAcceptedSocketL (uint32 aId)
uint8 * GetRecvData (int32 *aLength)
uint8 * GetSendData (int32 *aLength)
TPVSocketEvent BindAsync (OsclNetworkAddress &aAddress, int32 aTimeoutMsec=-1)
void CancelBind ()
TPVSocketEvent ListenAsync (uint32 qsize, int32 aTimeoutMsec=-1)
void CancelListen ()
TPVSocketEvent Connect (OsclNetworkAddress &aAddress, int32 aTimeoutMsec=-1)
void CancelConnect ()
TPVSocketEvent Shutdown (TPVSocketShutdown aHow, int32 aTimeoutMsec=-1)
void CancelShutdown ()
TPVSocketEvent Accept (int32 aTimeout=-1)
void CancelAccept ()
TPVSocketEvent Send (const uint8 *&aPtr, uint32 aLen, int32 aTimeoutMsec=-1)
void CancelSend ()
TPVSocketEvent Recv (uint8 *&aPtr, uint32 aMaxLen, int32 aTimeoutMsec=-1)
void CancelRecv ()
Static Public Member Functions
static OsclTCPSocketI * NewL (Oscl_DefAlloc &a, OsclSocketServI *aServ, OsclSocketObserver *aObserver, uint32 aId)
Detailed Description
Internal implementation class for OsclTCPSocket
Constructor & Destructor Documentation
virtual OsclTCPSocketI::~OsclTCPSocketI () [virtual]
Member Function Documentation
TPVSocketEvent OsclTCPSocketI::Accept (int32 aTimeout = -1) [inline]
References OsclAcceptMethod::Accept(), EPVSocketFailure, and OsclIPSocketI::iObserver.
TPVSocketEvent OsclTCPSocketI::BindAsync (OsclNetworkAddress & aAddress, int32 aTimeoutMsec = -1) [inline]
References OsclBindMethod::Bind(), EPVSocketFailure, EPVSocketNotImplemented, OsclSocketIBase::HasAsyncBind(), OsclIPSocketI::iAddress, OsclIPSocketI::iObserver, OsclNetworkAddress::ipAddr, OsclNetworkAddress::port, OsclNameString< __len >::Set(), and OsclNameString< __len >::Str().
void OsclTCPSocketI::CancelAccept () [inline]
References OsclSocketMethod::CancelMethod().
void OsclTCPSocketI::CancelBind () [inline]
References OsclSocketMethod::CancelMethod().
void OsclTCPSocketI::CancelConnect () [inline]
References OsclSocketMethod::CancelMethod().
void OsclTCPSocketI::CancelListen () [inline]
References OsclSocketMethod::CancelMethod().
void OsclTCPSocketI::CancelRecv () [inline]
References OsclSocketMethod::CancelMethod().
void OsclTCPSocketI::CancelSend () [inline]
References OsclSocketMethod::CancelMethod().
void OsclTCPSocketI::CancelShutdown () [inline]
References OsclSocketMethod::CancelMethod().
int32 OsclTCPSocketI::Close () [virtual]
Implements OsclIPSocketI.
TPVSocketEvent OsclTCPSocketI::Connect (OsclNetworkAddress & aAddress, int32 aTimeoutMsec = -1) [inline]
References OsclConnectMethod::Connect(), EPVSocketFailure, and OsclIPSocketI::iObserver.
OsclTCPSocketI* OsclTCPSocketI::GetAcceptedSocketL (uint32 aId)
uint8 * OsclTCPSocketI::GetRecvData (int32 * aLength) [inline, virtual]
Implements OsclIPSocketI.
References OsclRecvMethod::GetRecvData().
uint8 * OsclTCPSocketI::GetSendData (int32 * aLength) [inline, virtual]
Implements OsclIPSocketI.
References OsclSendMethod::GetSendData().
int32 OsclTCPSocketI::Listen (int aQueueSize) [inline]
References OsclIPSocketI::iSocket, and OsclSocketI::Listen().
TPVSocketEvent OsclTCPSocketI::ListenAsync (uint32 qsize, int32 aTimeoutMsec = -1) [inline]
References EPVSocketFailure, EPVSocketNotImplemented, OsclSocketIBase::HasAsyncListen(), OsclIPSocketI::iObserver, and OsclListenMethod::Listen().
static OsclTCPSocketI* OsclTCPSocketI::NewL (Oscl_DefAlloc & a, OsclSocketServI * aServ, OsclSocketObserver * aObserver, uint32 aId) [static]
TPVSocketEvent OsclTCPSocketI::Recv (uint8 *& aPtr, uint32 aMaxLen, int32 aTimeoutMsec = -1) [inline]
References EPVSocketFailure, OsclIPSocketI::iObserver, and OsclRecvMethod::Recv().
TPVSocketEvent OsclTCPSocketI::Send (const uint8 *& aPtr, uint32 aLen, int32 aTimeoutMsec = -1) [inline]
References EPVSocketFailure, OsclIPSocketI::iObserver, and OsclSendMethod::Send().
TPVSocketEvent OsclTCPSocketI::Shutdown (TPVSocketShutdown aHow, int32 aTimeoutMsec = -1) [inline]
References EPVSocketFailure, OsclIPSocketI::iObserver, and OsclShutdownMethod::Shutdown().
TPVSocketEvent OsclTCPSocketI::ThreadLogoff ()
Reimplemented from OsclIPSocketI.
TPVSocketEvent OsclTCPSocketI::ThreadLogon (OsclSocketServI * aServ, OsclSocketObserver * aObserver)
The documentation for this class was generated from the following file:
oscl_tcp_socket.h
OSCL API
Posting Version: CORE_9.005.1.1