oscl: HeapBase Class Reference
HeapBase Class Reference
[OSCL Memory]
#include <oscl_mem.h>
Public Member Functions
HeapBase ()
virtual ~HeapBase ()
Static Public Member Functions
static void * operator new (size_t aSize)
static void * operator new[] (size_t aSize)
static void * operator new[] (size_t aSize, const char *aFile=NULL, const int aLine=0)
static void * operator new (size_t aSize, void *aPtr)
static void operator delete (void *aPtr)
static void operator delete[] (void *aPtr)
Detailed Description
HeapBase is the base class for all classes that allocates memory.
HeapBase has overloaded new and delete operators.
Derived from _OsclHeapBase providing CBase* alike pointer and virtual destructor for cleanupstack to Push and Pop for cleanup when leave occurs.
HeapBase has a virtual destructor which calls the destructor of all the derived classes.
Constructor & Destructor Documentation
HeapBase::HeapBase () [inline]
virtual HeapBase::~HeapBase () [inline, virtual]
Member Function Documentation
static void HeapBase::operator delete (void * aPtr) [inline, static]
References _oscl_free().
static void HeapBase::operator delete[] (void * aPtr) [inline, static]
References _oscl_free().
static void* HeapBase::operator new (size_t aSize, void * aPtr) [inline, static]
static void* HeapBase::operator new (size_t aSize) [inline, static]
References _oscl_default_new().
static void* HeapBase::operator new[] (size_t aSize, const char * aFile = NULL, const int aLine = 0) [inline, static]
References _oscl_default_new(), and OSCL_UNUSED_ARG.
static void* HeapBase::operator new[] (size_t aSize) [inline, static]
References _oscl_default_new().
The documentation for this class was generated from the following file:
oscl_mem.h
OSCL API
Posting Version: CORE_9.005.1.1