oscl: CHeapRep Class Reference
CHeapRep Class Reference
[OSCL Util]
#include <oscl_string_rep.h>
Public Member Functions
CHeapRep ()
OSCL_IMPORT_REF bool set (uint32, const char *, Oscl_DefAlloc &)
OSCL_IMPORT_REF bool set (uint32, const oscl_wchar *, Oscl_DefAlloc &)
OSCL_IMPORT_REF bool append (uint32, const char *, uint32, const char *, Oscl_DefAlloc &)
OSCL_IMPORT_REF bool append (uint32, const oscl_wchar *, uint32, const oscl_wchar *, Oscl_DefAlloc &)
OSCL_IMPORT_REF void add_ref ()
OSCL_IMPORT_REF void remove_ref (Oscl_DefAlloc &)
Static Public Member Functions
static OSCL_IMPORT_REF void set_rep (CHeapRep *&, Oscl_DefAlloc &, const char *, uint32)
static OSCL_IMPORT_REF void set_rep (CHeapRep *&, Oscl_DefAlloc &, const oscl_wchar *, uint32)
static OSCL_IMPORT_REF void append_rep (CHeapRep *&, Oscl_DefAlloc &, const char *, uint32)
static OSCL_IMPORT_REF void append_rep (CHeapRep *&, Oscl_DefAlloc &, const oscl_wchar *, uint32)
static OSCL_IMPORT_REF void assign (CHeapRep *&, CHeapRep *, Oscl_DefAlloc &)
Data Fields
uint32 refcount
OsclAny * buffer
uint32 maxsize
uint32 size
Detailed Description
For internal use only-- heap string representation
Constructor & Destructor Documentation
CHeapRep::CHeapRep () [inline]
Member Function Documentation
OSCL_IMPORT_REF void CHeapRep::add_ref ()
OSCL_IMPORT_REF bool CHeapRep::append (uint32 , const oscl_wchar * , uint32 , const oscl_wchar * , Oscl_DefAlloc &)
OSCL_IMPORT_REF bool CHeapRep::append (uint32 , const char * , uint32 , const char * , Oscl_DefAlloc &)
static OSCL_IMPORT_REF void CHeapRep::append_rep (CHeapRep *& , Oscl_DefAlloc & , const oscl_wchar * , uint32) [static]
static OSCL_IMPORT_REF void CHeapRep::append_rep (CHeapRep *& , Oscl_DefAlloc & , const char * , uint32) [static]
static OSCL_IMPORT_REF void CHeapRep::assign (CHeapRep *& , CHeapRep * , Oscl_DefAlloc &) [static]
Referenced by OSCL_wHeapString< Alloc >::operator=(), OSCL_HeapString< Alloc >::operator=(), OSCL_HeapString< Alloc >::OSCL_HeapString(), and OSCL_wHeapString< Alloc >::OSCL_wHeapString().
OSCL_IMPORT_REF void CHeapRep::remove_ref (Oscl_DefAlloc &)
Referenced by OSCL_HeapString< Alloc >::~OSCL_HeapString(), and OSCL_wHeapString< Alloc >::~OSCL_wHeapString().
OSCL_IMPORT_REF bool CHeapRep::set (uint32 , const oscl_wchar * , Oscl_DefAlloc &)
OSCL_IMPORT_REF bool CHeapRep::set (uint32 , const char * , Oscl_DefAlloc &)
static OSCL_IMPORT_REF void CHeapRep::set_rep (CHeapRep *& , Oscl_DefAlloc & , const oscl_wchar * , uint32) [static]
static OSCL_IMPORT_REF void CHeapRep::set_rep (CHeapRep *& , Oscl_DefAlloc & , const char * , uint32) [static]
Field Documentation
OsclAny* CHeapRep::buffer
Referenced by OSCL_wHeapString< Alloc >::get_cstr(), OSCL_HeapString< Alloc >::get_cstr(), OSCL_wHeapString< Alloc >::get_str(), and OSCL_HeapString< Alloc >::get_str().
uint32 CHeapRep::maxsize
Referenced by OSCL_wHeapString< Alloc >::get_maxsize(), and OSCL_HeapString< Alloc >::get_maxsize().
uint32 CHeapRep::refcount
uint32 CHeapRep::size
Referenced by OSCL_wHeapString< Alloc >::get_size(), OSCL_HeapString< Alloc >::get_size(), OSCL_wHeapString< Alloc >::set(), and OSCL_HeapString< Alloc >::set().
The documentation for this class was generated from the following file:
oscl_string_rep.h
OSCL API
Posting Version: CORE_9.005.1.1