oscl: OsclMemStatsNode Class Reference
OsclMemStatsNode Class Reference
[OSCL Memory]
#include <oscl_mem_audit.h>
Public Member Functions
OsclMemStatsNode ()
void reset ()
~OsclMemStatsNode ()
void * operator new (oscl_memsize_t size)
void * operator new (oscl_memsize_t size, OsclMemStatsNode *ptr)
void operator delete (void *ptr) throw ()
Data Fields
MM_Stats_t * pMMStats
MM_FailInsertParam * pMMFIParam
char * tag
Constructor & Destructor Documentation
OsclMemStatsNode::OsclMemStatsNode () [inline]
References NULL, pMMFIParam, pMMStats, and tag.
OsclMemStatsNode::~OsclMemStatsNode () [inline]
References Oscl_TAlloc< T, Alloc >::deallocate(), OSCL_DELETE, pMMFIParam, pMMStats, and tag.
Member Function Documentation
void OsclMemStatsNode::operator delete (void * ptr) throw () [inline]
References Oscl_TAlloc< T, Alloc >::deallocate().
void* OsclMemStatsNode::operator new (oscl_memsize_t size, OsclMemStatsNode * ptr) [inline]
References OSCL_UNUSED_ARG.
void* OsclMemStatsNode::operator new (oscl_memsize_t size) [inline]
References Oscl_TAlloc< T, Alloc >::allocate(), and OSCL_UNUSED_ARG.
void OsclMemStatsNode::reset () [inline]
References pMMFIParam, pMMStats, MM_FailInsertParam::reset(), and MM_Stats_t::reset().
Field Documentation
MM_FailInsertParam* OsclMemStatsNode::pMMFIParam
Referenced by OsclMemStatsNode(), reset(), and ~OsclMemStatsNode().
MM_Stats_t* OsclMemStatsNode::pMMStats
Referenced by OsclMemStatsNode(), reset(), and ~OsclMemStatsNode().
char* OsclMemStatsNode::tag
Referenced by OsclMemStatsNode(), and ~OsclMemStatsNode().
The documentation for this class was generated from the following file:
oscl_mem_audit.h
OSCL API
Posting Version: CORE_9.005.1.1