oscl: OsclMemBasicAllocator Class Reference
OsclMemBasicAllocator Class Reference
[OSCL Memory]
#include <oscl_mem.h>
Public Member Functions
OsclAny * allocate (const uint32 n)
void deallocate (OsclAny *p)
Detailed Description
A simple allocator class that does not use the memory management.
Note: this allocator is for internal use by Oscl only. Higher level code should use OsclMemAllocator.
Member Function Documentation
OsclAny* OsclMemBasicAllocator::allocate (const uint32 n) [inline, virtual]
This API throws an exception when malloc returns NULL. n must be greater than 0.
Returns:
pointer (or Leave with OsclErrNoMemory)
Implements Oscl_DefAlloc.
References _oscl_malloc(), OsclError::LeaveIfNull(), and oscl_memset().
Referenced by OsclMemBasicAllocDestructDealloc< T >::allocate().
void OsclMemBasicAllocator::deallocate (OsclAny * p) [inline, virtual]
Implements Oscl_DefAlloc.
References _oscl_free().
Referenced by OsclMemBasicAllocDestructDealloc< T >::deallocate().
The documentation for this class was generated from the following file:
oscl_mem.h
OSCL API
Posting Version: CORE_9.005.1.1