oscl: OsclTimer< Alloc > Class Template Reference
OsclTimer< Alloc > Class Template Reference
#include <oscl_timer.h>
Data Structures
struct _TimerEntry
Public Types
typedef CallbackTimer< Alloc > callback_timer_type
Public Member Functions
OsclTimer (const char *name, uint32 frequency=1, int32 priority=OsclActiveObject::EPriorityNominal)
virtual ~OsclTimer ()
void SetObserver (OsclTimerObserver *obs)
void SetFrequency (uint32 frequency)
void SetExactFrequency (uint32 frequency)
void Request (int32 timerID, int32 timeoutInfo, int32 cycles, OsclTimerObserver *obs=0, bool recurring=0)
void Cancel (int32 timerID, int32 timeoutInfo=-1)
void Clear ()
Protected Member Functions
void TimerBaseElapsed ()
Friends
class CallbackTimer< Alloc >
template<class Alloc>
class OsclTimer< Alloc >
Member Typedef Documentation
template<class Alloc > typedef CallbackTimer<Alloc> OsclTimer< Alloc >::callback_timer_type
Constructor & Destructor Documentation
template<class Alloc > OsclTimer< Alloc >::OsclTimer (const char * name, uint32 frequency = 1, int32 priority = OsclActiveObject::EPriorityNominal) [inline]
Constructor
Parameters:
frequency The frequency of the timer in cycles/second. A value of 1 means the timer will cycle in 1 second intervals.
References OSCL_LEAVE, OSCL_PLACEMENT_NEW, OsclErrArgument, and OsclTimer< Alloc >::SetFrequency().
template<class Alloc > OsclTimer< Alloc >::~OsclTimer () [inline, virtual]
References Oscl_Vector< T, Alloc >::begin(), OsclTimerObject::Cancel(), Oscl_TAlloc< T, Alloc >::deallocate(), Oscl_Vector< T, Alloc >::end(), and NULL.
Member Function Documentation
template<class Alloc > void OsclTimer< Alloc >::Cancel (int32 timerID, int32 timeoutInfo = -1) [inline]
Cancel a timer
Parameters:
timerID used to identify the timer to cancel.
timeoutInfo if not set to -1, this value will be used as additional matching criteria to cancel a timer.
References Oscl_Vector< T, Alloc >::begin(), Oscl_TAlloc< T, Alloc >::deallocate(), Oscl_Vector< T, Alloc >::end(), Oscl_Vector< T, Alloc >::erase(), and Oscl_Vector< T, Alloc >::push_back().
Referenced by OsclTimer< Alloc >::TimerBaseElapsed().
template<class Alloc > void OsclTimer< Alloc >::Clear () [inline]
Cancel all pending timers.
References Oscl_Vector< T, Alloc >::begin(), Oscl_Vector< T, Alloc >::clear(), Oscl_TAlloc< T, Alloc >::deallocate(), and Oscl_Vector< T, Alloc >::end().
template<class Alloc > void OsclTimer< Alloc >::Request (int32 timerID, int32 timeoutInfo, int32 cycles, OsclTimerObserver * obs = 0, bool recurring = 0) [inline]
Request a timer
Parameters:
timerID used to identify the timer for cancellation. This value will be returned as part of the timeout event.
timeoutInfo for user info. Returned to the observer on a timeout event
cycles the number of cycles to wait before a timeout event. If the timer frequency is 1 and the cycles are set to 2, then the timeout event will occur in 2 seconds.
obs a local observer object to be called on a timeout event. This observer overides the global observer if set.
References Oscl_Vector< T, Alloc >::push_back(), OsclTimerObject::RunIfNotReady(), and OsclTickCount::TickCount().
Referenced by OsclTimer< Alloc >::TimerBaseElapsed().
template<class Alloc > void OsclTimer< Alloc >::SetExactFrequency (uint32 frequency) [inline]
Set the exact frequency of the timer in microsecond.
Parameters:
frequency A value of 1 means the timer will cycle in one microsecond intervals, 1000 means millisecond intervals, etc.
References OsclTickCount::TickCountPeriod().
template<class Alloc > void OsclTimer< Alloc >::SetFrequency (uint32 frequency) [inline]
Set the frequency of the timer in cycles/second.
Parameters:
frequency A value of 1 means the timer will cycle in one second intervals, 1000 means millisecond intervals, etc.
References OsclTickCount::TickCountPeriod().
Referenced by OsclTimer< Alloc >::OsclTimer().
template<class Alloc > void OsclTimer< Alloc >::SetObserver (OsclTimerObserver * obs) [inline]
Set the global observer. Each timer can request a local observer, which if set overrides the global observer.
Parameters:
obs observer object.
template<class Alloc > void OsclTimer< Alloc >::TimerBaseElapsed () [inline, protected, virtual]
Implements CallbackTimerObserver.
References Oscl_Vector< T, Alloc >::begin(), OsclTimer< Alloc >::Cancel(), Oscl_Vector< T, Alloc >::clear(), Oscl_TAlloc< T, Alloc >::deallocate(), Oscl_Vector_Base::empty(), Oscl_Vector< T, Alloc >::end(), Oscl_Vector< T, Alloc >::erase(), OSCL_ABS, OSCL_MAX, OsclTimer< Alloc >::Request(), OsclTimerObject::RunIfNotReady(), OsclTickCount::TickCount(), and OsclTimerObserver::TimeoutOccurred().
Friends And Related Function Documentation
template<class Alloc > friend class CallbackTimer< Alloc > [friend]
The documentation for this class was generated from the following file:
oscl_timer.h
OSCL API
Posting Version: CORE_9.005.1.1