oscl: GetHostByNameParam Class Reference
GetHostByNameParam Class Reference
#include <oscl_dns_param.h>
Public Types
enum { addressListCapacity = 10 }
Public Member Functions
void Destroy ()
~GetHostByNameParam ()
void PersistHostAddress (const OsclNetworkAddress &addr)
bool canPersistMoreHostAddresses ()
Static Public Member Functions
static GetHostByNameParam * Create (const char *name, OsclNetworkAddress *&addr, Oscl_Vector< OsclNetworkAddress, OsclMemAllocator > *aAddressList)
Data Fields
char * iName
OsclNetworkAddress * iAddr
Oscl_Vector
< OsclNetworkAddress,
OsclMemAllocator > * iAddressList
Member Enumeration Documentation
anonymous enum
Enumerator:
addressListCapacity
Constructor & Destructor Documentation
GetHostByNameParam::~GetHostByNameParam ()
Member Function Documentation
bool GetHostByNameParam::canPersistMoreHostAddresses () [inline]
References Oscl_Vector_Base::capacity(), iAddr, iAddressList, OsclNetworkAddress::ipAddr, OSCL_STATIC_CAST, oscl_strcmp(), Oscl_Vector_Base::size(), and OsclNameString< __len >::Str().
static GetHostByNameParam* GetHostByNameParam::Create (const char * name, OsclNetworkAddress *& addr, Oscl_Vector< OsclNetworkAddress, OsclMemAllocator > * aAddressList) [static]
void GetHostByNameParam::Destroy () [virtual]
Implements DNSRequestParam.
void GetHostByNameParam::PersistHostAddress (const OsclNetworkAddress & addr) [inline]
References Oscl_Vector_Base::capacity(), iAddr, iAddressList, OsclNetworkAddress::ipAddr, OSCL_STATIC_CAST, oscl_strcmp(), Oscl_Vector< T, Alloc >::push_back(), OsclNameString< __len >::Set(), Oscl_Vector_Base::size(), and OsclNameString< __len >::Str().
Field Documentation
OsclNetworkAddress* GetHostByNameParam::iAddr
Referenced by canPersistMoreHostAddresses(), and PersistHostAddress().
Oscl_Vector<OsclNetworkAddress, OsclMemAllocator>* GetHostByNameParam::iAddressList
Referenced by canPersistMoreHostAddresses(), and PersistHostAddress().
char* GetHostByNameParam::iName
The documentation for this class was generated from the following file:
oscl_dns_param.h
OSCL API
Posting Version: CORE_9.005.1.1