oscl: OsclUDPSocketI Class Reference
OsclUDPSocketI Class Reference
#include <oscl_udp_socket.h>
Public Member Functions
virtual ~OsclUDPSocketI ()
int32 Close ()
int32 JoinMulticastGroup (OsclIpMReq &aMReq)
int32 SetMulticastTTL (int32 aTTL)
uint8 * GetRecvData (int32 *aLength)
uint8 * GetSendData (int32 *aLength)
TPVSocketEvent ThreadLogoff ()
TPVSocketEvent ThreadLogon (OsclSocketServI *aServ, OsclSocketObserver *aObserver)
TPVSocketEvent BindAsync (OsclNetworkAddress &aAddress, int32 aTimeoutMsec=-1)
void CancelBind ()
TPVSocketEvent SendTo (const uint8 *&aPtr, uint32 aLen, OsclNetworkAddress &aAddress, int32 aTimeoutMsec=-1)
void CancelSendTo ()
TPVSocketEvent RecvFrom (uint8 *&aPtr, uint32 aMaxLen, OsclNetworkAddress &aAddress, int32 aTimeoutMsec=-1, uint32 aMultiMaxLen=0, Oscl_Vector< uint32, OsclMemAllocator > *aPacketLen=NULL, Oscl_Vector< OsclNetworkAddress, OsclMemAllocator > *aPacketSource=NULL)
void CancelRecvFrom ()
Static Public Member Functions
static OsclUDPSocketI * NewL (Oscl_DefAlloc &a, OsclSocketServI *aServ, OsclSocketObserver *aObserver, uint32 aId)
Detailed Description
Internal implementation class for OsclUDPSocket
Constructor & Destructor Documentation
virtual OsclUDPSocketI::~OsclUDPSocketI () [virtual]
Member Function Documentation
TPVSocketEvent OsclUDPSocketI::BindAsync (OsclNetworkAddress & aAddress, int32 aTimeoutMsec = -1) [inline]
References OsclBindMethod::Bind(), EPVSocketFailure, EPVSocketNotImplemented, OsclSocketIBase::HasAsyncBind(), OsclIPSocketI::iAddress, OsclIPSocketI::iObserver, OsclNetworkAddress::ipAddr, OsclNetworkAddress::port, OsclNameString< __len >::Set(), and OsclNameString< __len >::Str().
void OsclUDPSocketI::CancelBind () [inline]
References OsclSocketMethod::CancelMethod().
void OsclUDPSocketI::CancelRecvFrom () [inline]
References OsclSocketMethod::CancelMethod().
void OsclUDPSocketI::CancelSendTo () [inline]
References OsclSocketMethod::CancelMethod().
int32 OsclUDPSocketI::Close () [virtual]
Implements OsclIPSocketI.
uint8 * OsclUDPSocketI::GetRecvData (int32 * aLength) [inline, virtual]
Implements OsclIPSocketI.
References OsclRecvFromMethod::GetRecvData().
uint8 * OsclUDPSocketI::GetSendData (int32 * aLength) [inline, virtual]
Implements OsclIPSocketI.
References OsclSendToMethod::GetSendData().
int32 OsclUDPSocketI::JoinMulticastGroup (OsclIpMReq & aMReq)
static OsclUDPSocketI* OsclUDPSocketI::NewL (Oscl_DefAlloc & a, OsclSocketServI * aServ, OsclSocketObserver * aObserver, uint32 aId) [static]
TPVSocketEvent OsclUDPSocketI::RecvFrom (uint8 *& aPtr, uint32 aMaxLen, OsclNetworkAddress & aAddress, int32 aTimeoutMsec = -1, uint32 aMultiMaxLen = 0, Oscl_Vector< uint32, OsclMemAllocator > * aPacketLen = NULL, Oscl_Vector< OsclNetworkAddress, OsclMemAllocator > * aPacketSource = NULL) [inline]
References EPVSocketFailure, OsclIPSocketI::iObserver, and OsclRecvFromMethod::RecvFrom().
TPVSocketEvent OsclUDPSocketI::SendTo (const uint8 *& aPtr, uint32 aLen, OsclNetworkAddress & aAddress, int32 aTimeoutMsec = -1) [inline]
References EPVSocketFailure, OsclIPSocketI::iObserver, and OsclSendToMethod::SendTo().
int32 OsclUDPSocketI::SetMulticastTTL (int32 aTTL)
TPVSocketEvent OsclUDPSocketI::ThreadLogoff ()
Reimplemented from OsclIPSocketI.
TPVSocketEvent OsclUDPSocketI::ThreadLogon (OsclSocketServI * aServ, OsclSocketObserver * aObserver)
The documentation for this class was generated from the following file:
oscl_udp_socket.h
OSCL API
Posting Version: CORE_9.005.1.1