oscl: OsclSingletonRegistryEx Class Reference
OsclSingletonRegistryEx Class Reference
[OSCL Error]
#include <oscl_error.h>
Static Public Member Functions
static OsclAny * getInstance (uint32 ID)
static void registerInstance (OsclAny *ptr, uint32 ID)
static OsclAny * lockAndGetInstance (uint32 ID)
static void registerInstanceAndUnlock (OsclAny *ptr, uint32 ID)
Member Function Documentation
static OsclAny* OsclSingletonRegistryEx::getInstance (uint32 ID) [inline, static]
References OsclError::Leave(), and OSCL_ASSERT.
static OsclAny* OsclSingletonRegistryEx::lockAndGetInstance (uint32 ID) [inline, static]
References OsclError::Leave(), and OSCL_ASSERT.
static void OsclSingletonRegistryEx::registerInstance (OsclAny * ptr, uint32 ID) [inline, static]
References OsclError::Leave(), and OSCL_ASSERT.
static void OsclSingletonRegistryEx::registerInstanceAndUnlock (OsclAny * ptr, uint32 ID) [inline, static]
References OsclError::Leave(), and OSCL_ASSERT.
The documentation for this class was generated from the following file:
oscl_error.h
OSCL API
Posting Version: CORE_9.005.1.1