oscl: OsclNameString< __len > Class Template Reference
OsclNameString< __len > Class Template Reference
[OSCL Error]
#include <oscl_namestring.h>
Public Member Functions
OsclNameString ()
OsclNameString (const char a[])
OsclNameString (uint8 *a)
void Set (uint8 *a)
void Set (const char a[])
uint8 * Str () const
int32 MaxLen () const
Detailed Description
template<int __len>
class OsclNameString< __len >
Name string class appropriate for passing short constant ASCII strings around. All strings are automatically truncated and null-terminated.
Constructor & Destructor Documentation
template<int __len> OsclNameString< __len >::OsclNameString () [inline]
template<int __len> OsclNameString< __len >::OsclNameString (const char a[]) [inline]
template<int __len> OsclNameString< __len >::OsclNameString (uint8 * a) [inline]
Member Function Documentation
template<int __len> int32 OsclNameString< __len >::MaxLen () const [inline]
template<int __len> void OsclNameString< __len >::Set (const char a[]) [inline]
template<int __len> void OsclNameString< __len >::Set (uint8 * a) [inline]
Set the string to the input value. The string will be truncated to fit the storage class and automatically null-terminated.
Parameters:
a (input param): null-terminated character string.
Referenced by OsclUDPSocketI::BindAsync(), OsclTCPSocketI::BindAsync(), OsclNameString< PVNETWORKADDRESS_LEN >::OsclNameString(), GetHostByNameParam::PersistHostAddress(), and OsclNameString< PVNETWORKADDRESS_LEN >::Set().
template<int __len> uint8* OsclNameString< __len >::Str () const [inline]
Referenced by OsclUDPSocketI::BindAsync(), OsclTCPSocketI::BindAsync(), GetHostByNameParam::canPersistMoreHostAddresses(), OsclNetworkAddress::operator==(), and GetHostByNameParam::PersistHostAddress().
The documentation for this class was generated from the following file:
oscl_namestring.h
OSCL API
Posting Version: CORE_9.005.1.1