oscl: OsclError Class Reference
OsclError Class Reference
[OSCL Error]
#include <oscl_error.h>
Static Public Member Functions
static OSCL_IMPORT_REF void PushL (_OsclHeapBase *aPtr)
static OSCL_IMPORT_REF void PushL (OsclAny *aPtr)
static OSCL_IMPORT_REF void PushL (OsclTrapItem anItem)
static OSCL_IMPORT_REF void Pop ()
static OSCL_IMPORT_REF void Pop (int32 aCount)
static OSCL_IMPORT_REF void PopDealloc ()
static OSCL_IMPORT_REF void PopDealloc (int32 aCount)
static OSCL_IMPORT_REF void Leave (int32 aReason)
static OSCL_IMPORT_REF void LeaveIfNull (OsclAny *a)
static OSCL_IMPORT_REF void LeaveIfError (int32 aReason)
Detailed Description
User Error class
Member Function Documentation
static OSCL_IMPORT_REF void OsclError::Leave (int32 aReason) [static]
Do a Leave error, with the given reason code. When a leave occurs, all items on the cleanup stack for the current trap level will be destroyed, and execution will jump to the trap handler.
Referenced by OsclSocketMethod::ConstructL(), OsclDNSRequestAO::ConstructL(), OsclTLSRegistryEx::getInstance(), OsclSingletonRegistryEx::getInstance(), OsclSingletonRegistryEx::lockAndGetInstance(), OsclBuf::NewL(), OsclTLSRegistryEx::registerInstance(), OsclSingletonRegistryEx::registerInstance(), and OsclSingletonRegistryEx::registerInstanceAndUnlock().
static OSCL_IMPORT_REF void OsclError::LeaveIfError (int32 aReason) [static]
Evaluate the input parameter, and if it is an error code (non-zero), then do a Leave with the provided reason code.
static OSCL_IMPORT_REF void OsclError::LeaveIfNull (OsclAny * a) [static]
Evaluate the input parameter, and if it is null, do a Leave with OsclErrNoMemory reason code.
Referenced by OsclMemBasicAllocator::allocate(), and OsclMemAllocator::allocate().
static OSCL_IMPORT_REF void OsclError::Pop (int32 aCount) [static]
Pop the cleanup stack N times
static OSCL_IMPORT_REF void OsclError::Pop () [static]
Pop the cleanup stack
static OSCL_IMPORT_REF void OsclError::PopDealloc (int32 aCount) [static]
PopDealloc N times
static OSCL_IMPORT_REF void OsclError::PopDealloc () [static]
Destroy the item on the top of the cleanup stack and pop it
static OSCL_IMPORT_REF void OsclError::PushL (OsclTrapItem anItem) [static]
Push an OsclTrapItem onto the cleanup stack
static OSCL_IMPORT_REF void OsclError::PushL (OsclAny * aPtr) [static]
Push an OsclAny item onto the cleanup stack.
static OSCL_IMPORT_REF void OsclError::PushL (_OsclHeapBase * aPtr) [static]
Cleanup stack operations. Push an _OsclHeapBase item onto the cleanup stack.
The documentation for this class was generated from the following file:
oscl_error.h
OSCL API
Posting Version: CORE_9.005.1.1