oscl: OsclSocketRequestAO Class Reference
OsclSocketRequestAO Class Reference
#include <oscl_socket_method.h>
Public Member Functions
void ConstructL ()
Protected Member Functions
OsclSocketRequestAO (OsclSocketMethod &aContainer, const char *name)
virtual ~OsclSocketRequestAO ()
OsclAny * NewRequest (const uint32 size)
void CleanupParam (bool deallocate=false)
void Abort ()
void RequestDone ()
int GetSocketError ()
void DoCancel ()
void Run ()
virtual void Success ()
OsclSocketI * SocketI ()
OsclSocketObserver * SocketObserver ()
uint32 Id ()
Oscl_DefAlloc & Alloc ()
Protected Attributes
OsclSocketMethod & iContainer
int32 iSocketError
SocketRequestParam * iParam
uint32 iParamSize
Friends
class OsclSocketI
class OsclSocketMethod
class OsclSocketRequest
Detailed Description
This is the base class for all the AOs that interact with the socket server. This object is contained within an OsclSocketMethod object
Constructor & Destructor Documentation
OsclSocketRequestAO::OsclSocketRequestAO (OsclSocketMethod & aContainer, const char * name) [inline, protected]
virtual OsclSocketRequestAO::~OsclSocketRequestAO () [inline, protected, virtual]
References CleanupParam().
Member Function Documentation
void OsclSocketRequestAO::Abort () [inline, protected]
References OsclActiveObject::Cancel().
Referenced by OsclSocketMethod::AbortAll(), and OsclSocketMethod::MethodDone().
Oscl_DefAlloc& OsclSocketRequestAO::Alloc () [inline, protected]
References OsclIPSocketI::Alloc(), OsclSocketMethod::iContainer, and iContainer.
void OsclSocketRequestAO::CleanupParam (bool deallocate = false) [protected]
Referenced by ~OsclSocketRequestAO().
void OsclSocketRequestAO::ConstructL () [inline]
void OsclSocketRequestAO::DoCancel () [inline, protected, virtual]
Cancel request handler. This gets called by scheduler when the request is cancelled. The default routine will complete the request. If any additional action is needed, the derived class may override this. If the derived class does override DoCancel, it must complete the request.
Reimplemented from OsclActiveObject.
References OsclSocketIBase::CancelFxn(), iContainer, OsclSocketMethod::iSocketFxn, and SocketI().
Referenced by OsclSocketMethod::CancelMethod().
int OsclSocketRequestAO::GetSocketError () [inline, protected]
uint32 OsclSocketRequestAO::Id () [inline, protected]
References OsclSocketMethod::iContainer, iContainer, and OsclIPSocketI::iId.
OsclAny* OsclSocketRequestAO::NewRequest (const uint32 size) [protected]
void OsclSocketRequestAO::RequestDone () [inline, protected]
References OsclSocketMethod::Abort(), and iContainer.
void OsclSocketRequestAO::Run () [protected, virtual]
Handles an active object's request completion event.
A derived class must provide an implementation to handle the completed request. If appropriate, it may issue another request.
The function is called by the active scheduler when a request completion event occurs, i.e. after the active scheduler's WaitForAnyRequest() function completes.
Before calling this active object's Run() function, the active scheduler has:
1. decided that this is the highest priority active object with a completed request
2. marked this active object's request as complete (i.e. the request is no longer outstanding)
Run() runs under a trap harness in the active scheduler. If it leaves, then the active scheduler calls ExecError() to handle the leave.
Note that once the active scheduler's Start() function has been called, all user code is run under one of the program's active object's Run() or RunError() functions.
Implements PVActiveBase.
OsclSocketI* OsclSocketRequestAO::SocketI () [inline, protected]
References OsclSocketMethod::iContainer, iContainer, and OsclIPSocketI::iSocket.
Referenced by DoCancel().
OsclSocketObserver* OsclSocketRequestAO::SocketObserver () [inline, protected]
References OsclSocketMethod::iContainer, iContainer, and OsclIPSocketI::iObserver.
virtual void OsclSocketRequestAO::Success () [inline, protected, virtual]
Reimplemented in OsclRecvRequest, OsclRecvFromRequest, OsclSendRequest, and OsclSendToRequest.
Friends And Related Function Documentation
friend class OsclSocketI [friend]
friend class OsclSocketMethod [friend]
friend class OsclSocketRequest [friend]
Field Documentation
OsclSocketMethod& OsclSocketRequestAO::iContainer [protected]
Referenced by Alloc(), DoCancel(), Id(), RequestDone(), SocketI(), and SocketObserver().
SocketRequestParam* OsclSocketRequestAO::iParam [protected]
uint32 OsclSocketRequestAO::iParamSize [protected]
int32 OsclSocketRequestAO::iSocketError [protected]
The documentation for this class was generated from the following file:
oscl_socket_method.h
OSCL API
Posting Version: CORE_9.005.1.1