oscl: Oscl_DefAlloc Class Reference
Oscl_DefAlloc Class Reference
[OSCL Base]
#include <oscl_defalloc.h>
Public Member Functions
virtual OsclAny * allocate (const uint32 size)=0
virtual OsclAny * allocate_fl (const uint32 size, const char *file_name, const int line_num)
virtual void deallocate (OsclAny *p)=0
Member Function Documentation
virtual OsclAny* Oscl_DefAlloc::allocate (const uint32 size) [pure virtual]
Implements Oscl_Alloc.
Implemented in _OsclBasicAllocator, OsclMemAllocator, OsclMemBasicAllocator, OsclMemAllocDestructDealloc< T >, OsclMemBasicAllocDestructDealloc< T >, OsclMemPoolFixedChunkAllocator, OsclMemPoolResizableAllocator, and OsclReadyAlloc.
Referenced by allocate_fl().
virtual OsclAny* Oscl_DefAlloc::allocate_fl (const uint32 size, const char * file_name, const int line_num) [inline, virtual]
Reimplemented from Oscl_Alloc.
Reimplemented in OsclReadyAlloc.
References allocate(), and OSCL_UNUSED_ARG.
Referenced by OsclMemBasicAllocDestructDealloc< T >::allocate(), OsclMemAllocDestructDealloc< T >::allocate(), and OsclMemAllocator::allocate().
virtual void Oscl_DefAlloc::deallocate (OsclAny * p) [pure virtual]
Implements Oscl_Dealloc.
Implemented in _OsclBasicAllocator, OsclMemAllocator, OsclMemBasicAllocator, OsclMemAllocDestructDealloc< T >, OsclMemBasicAllocDestructDealloc< T >, OsclMemPoolFixedChunkAllocator, OsclMemPoolResizableAllocator, and OsclReadyAlloc.
Referenced by OsclErrorAllocator::deallocate().
The documentation for this class was generated from the following file:
oscl_defalloc.h
OSCL API
Posting Version: CORE_9.005.1.1