oscl: OsclTickCount Class Reference
OsclTickCount Class Reference
[OSCL Util]
#include <oscl_tickcount.h>
Static Public Member Functions
static uint32 TickCount ()
static uint32 TickCountFrequency ()
static uint32 TickCountPeriod ()
static uint32 TicksToMsec (uint32 ticks)
static uint32 MsecToTicks (uint32 msec)
Detailed Description
OsclTickCount class is used to retrieve the system tick count and the tick counter's frequency.
The maximum tick count value is equivalent to the maximum uint32 value.
Member Function Documentation
static uint32 OsclTickCount::MsecToTicks (uint32 msec) [static]
This function converts milliseconds to ticks
Returns:
ticks
static uint32 OsclTickCount::TickCount () [static]
This function returns the current system tick count
Returns:
returns the tick count
Referenced by OsclTimer< Alloc >::Request(), and OsclTimer< Alloc >::TimerBaseElapsed().
static uint32 OsclTickCount::TickCountFrequency () [static]
This function returns the tick frequency in ticks per second
Returns:
ticks per second
static uint32 OsclTickCount::TickCountPeriod () [static]
This function returns the tick period in microseconds per tick
Returns:
microseconds per tick
Referenced by OsclTimer< Alloc >::SetExactFrequency(), and OsclTimer< Alloc >::SetFrequency().
static uint32 OsclTickCount::TicksToMsec (uint32 ticks) [static]
This function converts ticks to milliseconds
Returns:
milliseconds
The documentation for this class was generated from the following file:
oscl_tickcount.h
OSCL API
Posting Version: CORE_9.005.1.1