oscl: CallbackTimer< Alloc > Class Template Reference
CallbackTimer< Alloc > Class Template Reference
#include <oscl_timer.h>
Public Member Functions
CallbackTimer (CallbackTimerObserver &aContainer, const char *name, int32 aPriority=OsclActiveObject::EPriorityNominal)
~CallbackTimer ()
void Run ()
template<class Alloc>
class CallbackTimer< Alloc >
Constructor & Destructor Documentation
template<class Alloc> CallbackTimer< Alloc >::CallbackTimer (CallbackTimerObserver & aContainer, const char * name, int32 aPriority = OsclActiveObject::EPriorityNominal) [inline]
References OsclTimerObject::AddToScheduler().
template<class Alloc> CallbackTimer< Alloc >::~CallbackTimer () [inline]
References OsclTimerObject::RemoveFromScheduler().
Member Function Documentation
template<class Alloc> void CallbackTimer< Alloc >::Run () [inline, virtual]
Handles an active object's request completion event.
A derived class must provide an implementation to handle the completed request. If appropriate, it may issue another request.
The function is called by the active scheduler when a request completion event occurs, i.e. after the active scheduler's WaitForAnyRequest() function completes.
Before calling this active object's Run() function, the active scheduler has:
1. decided that this is the highest priority active object with a completed request
2. marked this active object's request as complete (i.e. the request is no longer outstanding)
Run() runs under a trap harness in the active scheduler. If it leaves, then the active scheduler calls ExecError() to handle the leave.
Note that once the active scheduler's Start() function has been called, all user code is run under one of the program's active object's Run() or RunError() functions.
Implements PVActiveBase.
References OSCL_REQUEST_ERR_NONE, OsclTimerObject::Status(), and CallbackTimerObserver::TimerBaseElapsed().
The documentation for this class was generated from the following file:
oscl_timer.h
OSCL API
Posting Version: CORE_9.005.1.1