oscl: OsclPtr Class Reference
OsclPtr Class Reference
#include <oscl_file_async_read.h>
Public Member Functions
OsclPtr (uint8 *ptr, int32 &len, int32 max)
OsclPtr (const OsclPtr &d)
uint8 * Ptr ()
void SetLength (int32 l)
int32 Length ()
void Zero ()
void Set (OsclPtr &v)
void Set (uint8 *ptr, int32 len, int32 max)
void Append (OsclPtrC &v)
Constructor & Destructor Documentation
OsclPtr::OsclPtr (uint8 * ptr, int32 & len, int32 max) [inline]
OsclPtr::OsclPtr (const OsclPtr & d) [inline]
Member Function Documentation
void OsclPtr::Append (OsclPtrC & v) [inline]
References OsclPtrC::Length(), OSCL_ASSERT, oscl_memmove(), and OsclPtrC::Ptr().
int32 OsclPtr::Length () [inline]
uint8* OsclPtr::Ptr () [inline]
void OsclPtr::Set (uint8 * ptr, int32 len, int32 max) [inline]
void OsclPtr::Set (OsclPtr & v) [inline]
void OsclPtr::SetLength (int32 l) [inline]
References OSCL_ASSERT.
void OsclPtr::Zero () [inline]
The documentation for this class was generated from the following file:
oscl_file_async_read.h
OSCL API
Posting Version: CORE_9.005.1.1