oscl: OsclRefCounter Class Reference
OsclRefCounter Class Reference
[OSCL Base]
#include <oscl_refcounter.h>
Public Member Functions
virtual void addRef ()=0
virtual void removeRef ()=0
virtual uint32 getCount ()=0
virtual ~OsclRefCounter ()
Detailed Description
Interface class for OsclRefCounter implementations
Constructor & Destructor Documentation
virtual OsclRefCounter::~OsclRefCounter () [inline, virtual]
Member Function Documentation
virtual void OsclRefCounter::addRef () [pure virtual]
Add to the reference count
Implemented in OsclRefCounterDA, OsclRefCounterSA< DeallocType >, OsclRefCounterMTDA< LockType >, OsclRefCounterMTSA< DeallocType, LockType >, and Oscl_DefAllocWithRefCounter< DefAlloc >.
Referenced by OsclSharedPtr< TheClass >::Bind(), OsclRefCounterMemFrag::OsclRefCounterMemFrag(), and OsclSharedPtr< TheClass >::OsclSharedPtr().
virtual uint32 OsclRefCounter::getCount () [pure virtual]
Gets the current number of references
Implemented in OsclRefCounterDA, OsclRefCounterSA< DeallocType >, OsclRefCounterMTDA< LockType >, OsclRefCounterMTSA< DeallocType, LockType >, and Oscl_DefAllocWithRefCounter< DefAlloc >.
Referenced by OsclSharedPtr< TheClass >::get_count().
virtual void OsclRefCounter::removeRef () [pure virtual]
Delete from reference count
Implemented in OsclRefCounterDA, OsclRefCounterSA< DeallocType >, OsclRefCounterMTDA< LockType >, OsclRefCounterMTSA< DeallocType, LockType >, and Oscl_DefAllocWithRefCounter< DefAlloc >.
Referenced by OsclSharedPtr< TheClass >::Bind(), and OsclSharedPtr< TheClass >::~OsclSharedPtr().
The documentation for this class was generated from the following file:
oscl_refcounter.h
OSCL API
Posting Version: CORE_9.005.1.1