oscl: BufferState Class Reference
BufferState Class Reference
[OSCL Util]
#include <oscl_media_data.h>
Public Member Functions
BufferState (BufferFreeFuncPtr the_free_function, void *bufptr=0)
BufferState (BufferMgr *the_buf_mgr=0, void *bufptr=0)
void increment_refcnt ()
void decrement_refcnt ()
void bind (void *in_ptr, BufferFreeFuncPtr in_free_function)
void bind (void *in_ptr, BufferMgr *in_buf_mgr)
void * get_ptr ()
int32 get_refcount ()
BufferFreeFuncPtr get_free_function ()
BufferMgr * get_buf_mgr ()
void reset ()
Constructor & Destructor Documentation
BufferState::BufferState (BufferFreeFuncPtr the_free_function, void * bufptr = 0) [inline]
BufferState::BufferState (BufferMgr * the_buf_mgr = 0, void * bufptr = 0) [inline]
Member Function Documentation
void BufferState::bind (void * in_ptr, BufferMgr * in_buf_mgr) [inline]
void BufferState::bind (void * in_ptr, BufferFreeFuncPtr in_free_function) [inline]
void BufferState::decrement_refcnt () [inline]
References BufferMgr::BufferReleased().
Referenced by MediaData< ChainClass, max_frags, local_bufsize >::Clear(), and BufFragGroup< ChainClass, max_frags >::Clear().
BufferMgr* BufferState::get_buf_mgr () [inline]
BufferFreeFuncPtr BufferState::get_free_function () [inline]
void* BufferState::get_ptr () [inline]
int32 BufferState::get_refcount () [inline]
void BufferState::increment_refcnt () [inline]
Referenced by BufFragGroup< ChainClass, max_frags >::AddFragment().
void BufferState::reset () [inline]
The documentation for this class was generated from the following file:
oscl_media_data.h
OSCL API
Posting Version: CORE_9.005.1.1