oscl: OsclMemBasicAllocDestructDealloc< T > Class Template Reference
OsclMemBasicAllocDestructDealloc< T > Class Template Reference
[OSCL Memory]
#include <oscl_mem.h>
Public Member Functions
OsclAny * allocate (const uint32 size)
void deallocate (OsclAny *p)
void destruct_and_dealloc (OsclAny *p)
Detailed Description
template<class T>
class OsclMemBasicAllocDestructDealloc< T >
An OsclAllocDestructDealloc class that uses OsclMemBasicAllocator.
Member Function Documentation
template<class T > OsclAny* OsclMemBasicAllocDestructDealloc< T >::allocate (const uint32 size) [inline, virtual]
Implements Oscl_DefAlloc.
References OsclMemBasicAllocator::allocate(), Oscl_DefAlloc::allocate_fl(), and NULL.
template<class T > void OsclMemBasicAllocDestructDealloc< T >::deallocate (OsclAny * p) [inline, virtual]
Implements Oscl_DefAlloc.
References OsclMemBasicAllocator::deallocate().
Referenced by OsclMemBasicAllocDestructDealloc< T >::destruct_and_dealloc().
template<class T > void OsclMemBasicAllocDestructDealloc< T >::destruct_and_dealloc (OsclAny * p) [inline, virtual]
Implements OsclDestructDealloc.
References OsclMemBasicAllocDestructDealloc< T >::deallocate(), and OSCL_UNUSED_ARG.
The documentation for this class was generated from the following file:
oscl_mem.h
OSCL API
Posting Version: CORE_9.005.1.1