oscl: OSCL Util
OSCL Util
Data Structures
class OsclRegistryAccessClient
class OsclRegistryClient
class OsclRegistryClientImpl
class OsclRegistryAccessClientImpl
class OsclRegistryClientTlsImpl
class OsclRegistryAccessClientTlsImpl
class OsclRegistryAccessElement
class OsclComponentRegistryElement
class OsclComponentRegistryData
class OsclComponentRegistry
class OsclRegistryServTlsImpl
class OsclBinStream
class OsclBinIStream
class OsclBinIStreamLittleEndian
class OsclBinIStreamBigEndian
class OsclBinOStream
Class OsclBinOStream implements the basic stream functions for an output stream.
class OsclBinOStreamLittleEndian
Class OsclBinOStreamLittleEndian implements a binary output stream using little endian byte ordering.
class OsclBinOStreamBigEndian
Class OsclBinOStreamBigEndian implements a binary output stream using big endian byte ordering.
class MemAllocator< T >
class BufferMgr
class BufferState
class BufferFragment
class BufFragGroup< ChainClass, max_frags >
class MediaData< ChainClass, max_frags, local_bufsize >
class BufFragStatusClass
class MediaStatusClass
class OsclPriorityQueueBase
class OsclCompareLess< T >
class OsclPriorityQueue< Qelem, Alloc, Container, Compare >
class OsclRand
struct StrPtrLen
This data structure encapsulates a set of functions used to perform.
struct WStrPtrLen
This data structure encapsulates a set of functions used to perform.
struct StrCSumPtrLen
same as StrPtrLen, but includes checksum field and method to speed up querying
class OSCL_String
class OSCL_wString
class OSCL_HeapString< Alloc >
class OSCL_wHeapString< Alloc >
class OSCL_HeapStringA
class OSCL_wHeapStringA
class OSCL_StackString< MaxBufSize >
class OSCL_wStackString< MaxBufSize >
class OSCL_FastString
class OSCL_wFastString
class CHeapRep
class CStackRep
class CFastRep
class OsclTickCount
Files
file oscl_string_utils.h
Utilities to parse and convert strings.
file oscl_registry_access_client.h
Client-side implementation Registry Access implementation.
file oscl_registry_client.h
Client-side implementation of OsclRegistry.
file oscl_registry_client_impl.h
Client-side implementation of OsclRegistryInterface.
file oscl_registry_types.h
Common types used in Oscl registry interfaces.
file oscl_registry_serv_impl.h
Server-side implementation of OsclRegistry interfaces.
file oscl_registry_serv_impl.h
Server-side implementation of OsclRegistry interfaces.
file oscl_registry_serv_impl.h
Server-side implementation of OsclRegistry interfaces.
file oscl_bin_stream.h
Defines a set of binary stream classes which handle portable input / output of binary data regardless of the native byte order.
file oscl_math.h
Provides math functions.
file oscl_media_data.h
Defines a container class for media data made up of a collection of memory fragments.
file oscl_media_status.h
Defines a status values for the MediaData containers.
file oscl_priqueue.h
Implements a priority queue data structure similar to STL.
file oscl_rand.h
Provides pseudo-random number generation.
file oscl_snprintf.h
Provides a portable implementation of snprintf.
file oscl_str_ptr_len.h
Defines a data structure for string containment/manipulations where the storage for the string is maintained externally.
file oscl_string.h
Provides a standardized set of string containers that can be used in place of character arrays.
file oscl_string_containers.h
Provides a standardized set of string containers that can be used in place of character arrays.
file oscl_string_rep.h
Contains some internal implementation for string containers.
file oscl_string_uri.h
Utilities to unescape URIs.
file oscl_string_utf8.h
Utilities to validate and truncate UTF-8 encoded strings.
file oscl_string_xml.h
Utilities to escape special characters in XML strings.
file oscl_tickcount.h
Defines a data structure for string containment/manipulations where the storage for the string is maintained externally.
file oscl_utf8conv.h
Utilities to convert unicode to utf8 and vice versa.
Defines
#define oscl_isdigit(c) ((c) >= '0' && (c) <= '9')
#define OSCLTICKCOUNT_MAX_TICKS 0xffffffff
#define MAX_NUMBER_OF_BYTE_PER_UTF8 3
Typedefs
typedef OsclAny * OsclComponentFactory
typedef void(* BufferFreeFuncPtr)(void *)
typedef uint32 MediaTimestamp
typedef struct StrPtrLen StrPtrLen
This data structure encapsulates a set of functions used to perform.
typedef struct WStrPtrLen WStrPtrLen
This data structure encapsulates a set of functions used to perform.
typedef StrCSumPtrLen StrCSumPtrLen
same as StrPtrLen, but includes checksum field and method to speed up querying
typedef WStrPtrLen OSCL_TStrPtrLen
Enumerations
enum TOSCL_StringOp { EOSCL_StringOp_CompressASCII, EOSCL_StringOp_UTF16ToUTF8 }
enum TOSCL_wStringOp { EOSCL_wStringOp_ExpandASCII, EOSCL_wStringOp_UTF8ToUTF16 }
Functions
OSCL_IMPORT_REF const char * skip_whitespace (const char *ptr)
OSCL_IMPORT_REF char * skip_whitespace (char *ptr)
OSCL_IMPORT_REF const char * skip_whitespace (const char *start, const char *end)
OSCL_IMPORT_REF const char * skip_to_whitespace (const char *start, const char *end)
OSCL_IMPORT_REF const char * skip_to_line_term (const char *start_ptr, const char *end_ptr)
OSCL_IMPORT_REF const char * skip_whitespace_and_line_term (const char *start, const char *end)
OSCL_IMPORT_REF int extract_string (const char *in_ptr, char *outstring, int maxsize)
OSCL_IMPORT_REF int extract_string (const char *start, const char *end, char *outstring, int maxsize)
OSCL_IMPORT_REF bool PV_atoi (const char *buf, const char new_format, uint32 &value)
OSCL_IMPORT_REF bool PV_atoi (const char *buf, const char new_format, int length, uint32 &value)
OSCL_IMPORT_REF bool PV_atoi (const char *buf, const char new_format, int length, uint64 &value)
OSCL_IMPORT_REF bool PV_atof (const char *buf, OsclFloat &value)
OSCL_IMPORT_REF bool PV_atof (const char *buf, int length, OsclFloat &value)
OSCL_IMPORT_REF int oscl_abs (int aVal)
OSCL_COND_IMPORT_REF double oscl_log (double value)
OSCL_COND_IMPORT_REF double oscl_log10 (double value)
OSCL_COND_IMPORT_REF double oscl_sqrt (double value)
OSCL_COND_IMPORT_REF double oscl_pow (double x, double y)
OSCL_COND_IMPORT_REF double oscl_exp (double value)
OSCL_COND_IMPORT_REF double oscl_sin (double value)
OSCL_COND_IMPORT_REF double oscl_cos (double value)
OSCL_COND_IMPORT_REF double oscl_tan (double value)
OSCL_COND_IMPORT_REF double oscl_asin (double value)
OSCL_COND_IMPORT_REF double oscl_atan (double value)
OSCL_COND_IMPORT_REF double oscl_floor (double value)
OSCL_IMPORT_REF int32 oscl_snprintf (char *str, uint32 count, const char *fmt,...)
OSCL_IMPORT_REF int32 oscl_snprintf (oscl_wchar *str, uint32 count, const oscl_wchar *fmt,...)
OSCL_IMPORT_REF int32 oscl_vsnprintf (char *str, uint32 count, const char *fmt, va_list args)
OSCL_IMPORT_REF int32 oscl_vsnprintf (oscl_wchar *str, uint32 count, const oscl_wchar *fmt, va_list args)
OSCL_IMPORT_REF bool oscl_str_unescape_uri (const char *str_buf_in, char *str_buf_out, uint32 max_out_buf_bytes, uint32 max_bytes, uint32 &out_buf_len)
unescape any of the special escape sequence in the uri string
OSCL_IMPORT_REF bool oscl_str_unescape_uri (const OSCL_String &oscl_str_in, OSCL_String &oscl_str_out, uint32 &out_buf_len)
unescape any of the special escape sequence in the uri string
OSCL_IMPORT_REF bool oscl_str_is_valid_utf8 (const uint8 *str_buf, uint32 &num_valid_characters, uint32 max_bytes=0, uint32 max_char_2_valid=0, uint32 *num_byte_4_char=NULL)
Check if the input string contains any illegal UTF-8 character. The function scans the string and validate that each character is a valid utf-8. It stops at the first NULL character, invalid character or the max_byte value. The string is valid if and only if every character is a valid utf-8 character and the scanning stopped on a character boundary.
OSCL_IMPORT_REF int32 oscl_str_truncate_utf8 (uint8 *str_buf, uint32 max_char, uint32 max_bytes=0)
Truncates the UTF-8 string upto the required size.
OSCL_IMPORT_REF bool oscl_str_need_escape_xml (const char *str_buf, uint32 &num_escape_bytes, uint32 max_bytes=0)
Check if the input string contains any special ASCII character like &, <, >, ', ". The function scans the string and check if each character is a special character. It stops at the first NULL character (if max_bytes = 0), or the max_byte value.
OSCL_IMPORT_REF int32 oscl_str_escape_xml (const char *str_buf_in, char *str_buf_out, uint32 max_out_buf_bytes, uint32 max_bytes=0, uint32 *num_bytes_written=NULL)
Escape any of the following special characters in the string Special ASCII characters: &, <, >, ', ".
OSCL_IMPORT_REF int32 oscl_UTF8ToUnicode (const char *input, int32 inLength, oscl_wchar *output, int32 outLength)
Convert UTF8 byte sequence to Unicode UTF-16 string.
OSCL_IMPORT_REF int32 oscl_UnicodeToUTF8 (const oscl_wchar *input, int32 inLength, char *output, int32 outLength)
Convert UTF-16 Unicode string to UTF8 byte sequence.
BufferFragment * BufFragGroup::GetFragment (const int32 idx)
BufferState * BufFragGroup::GetBufferState (const int32 idx)
uint32 OSCL_HeapString::get_size () const
uint32 OSCL_wHeapString::get_size () const
uint32 OSCL_HeapString::get_maxsize () const
uint32 OSCL_wHeapString::get_maxsize () const
const chartype * OSCL_HeapString::get_cstr () const
const chartype * OSCL_wHeapString::get_cstr () const
chartype * OSCL_HeapString::get_str () const
chartype * OSCL_wHeapString::get_str () const
OSCL_HeapString::OSCL_HeapString ()
OSCL_wHeapString::OSCL_wHeapString ()
OSCL_HeapString::OSCL_HeapString (const chartype *cstr)
OSCL_wHeapString::OSCL_wHeapString (const chartype *cstr)
void OSCL_HeapString::set (const chartype *buf, uint32 length)
void OSCL_wHeapString::set (const chartype *buf, uint32 length)
void OSCL_HeapString::set (const other_chartype *buf, optype op)
void OSCL_wHeapString::set (const other_chartype *buf, optype op)
void OSCL_HeapString::set (const other_chartype *buf, uint32 length, optype op)
void OSCL_wHeapString::set (const other_chartype *buf, uint32 length, optype op)
OSCL_HeapString::OSCL_HeapString (const chartype *buf, uint32 length)
OSCL_wHeapString::OSCL_wHeapString (const chartype *buf, uint32 length)
OSCL_HeapString::OSCL_HeapString (const OSCL_HeapString &src)
OSCL_wHeapString::OSCL_wHeapString (const OSCL_wHeapString &src)
OSCL_HeapString::OSCL_HeapString (const OSCL_String &src)
OSCL_wHeapString::OSCL_wHeapString (const OSCL_wString &src)
OSCL_HeapString::~OSCL_HeapString ()
OSCL_wHeapString::~OSCL_wHeapString ()
OSCL_HeapString & OSCL_HeapString::operator= (const OSCL_HeapString &src)
OSCL_wHeapString & OSCL_wHeapString::operator= (const OSCL_wHeapString &src)
OSCL_HeapString & OSCL_HeapString::operator= (const OSCL_String &src)
OSCL_wHeapString & OSCL_wHeapString::operator= (const OSCL_wString &src)
OSCL_HeapString & OSCL_HeapString::operator= (const chartype *cstr)
OSCL_wHeapString & OSCL_wHeapString::operator= (const chartype *cstr)
uint32 OSCL_StackString::get_size () const
uint32 OSCL_wStackString::get_size () const
uint32 OSCL_StackString::get_maxsize () const
uint32 OSCL_wStackString::get_maxsize () const
const chartype * OSCL_StackString::get_cstr () const
const chartype * OSCL_wStackString::get_cstr () const
chartype * OSCL_StackString::get_str () const
chartype * OSCL_wStackString::get_str () const
OSCL_StackString::OSCL_StackString ()
OSCL_wStackString::OSCL_wStackString ()
OSCL_StackString::OSCL_StackString (const chartype *cstr)
OSCL_wStackString::OSCL_wStackString (const chartype *cstr)
void OSCL_StackString::set (const chartype *buf, uint32 length)
void OSCL_wStackString::set (const chartype *buf, uint32 length)
void OSCL_StackString::set (const other_chartype *buf, optype op)
void OSCL_wStackString::set (const other_chartype *buf, optype op)
void OSCL_StackString::set (const other_chartype *buf, uint32 length, optype op)
void OSCL_wStackString::set (const other_chartype *buf, uint32 length, optype op)
OSCL_StackString::OSCL_StackString (const chartype *buf, uint32 length)
OSCL_wStackString::OSCL_wStackString (const chartype *buf, uint32 length)
OSCL_StackString::OSCL_StackString (const OSCL_StackString &src)
OSCL_wStackString::OSCL_wStackString (const OSCL_wStackString &src)
OSCL_StackString::OSCL_StackString (const OSCL_String &src)
OSCL_wStackString::OSCL_wStackString (const OSCL_wString &src)
OSCL_StackString::~OSCL_StackString ()
OSCL_wStackString::~OSCL_wStackString ()
OSCL_StackString & OSCL_StackString::operator= (const OSCL_StackString &src)
OSCL_wStackString & OSCL_wStackString::operator= (const OSCL_wStackString &src)
OSCL_StackString & OSCL_StackString::operator= (const OSCL_String &src)
OSCL_wStackString & OSCL_wStackString::operator= (const OSCL_wString &src)
OSCL_StackString & OSCL_StackString::operator= (const chartype *cstr)
OSCL_wStackString & OSCL_wStackString::operator= (const chartype *cstr)
Variables
const int32 APPEND_MEDIA_AT_END = -1
const uint8 OSCL_ASCII_CASE_MAGIC_BIT = 0x20
Define Documentation
#define MAX_NUMBER_OF_BYTE_PER_UTF8 3
Define the maximum UTF8 representation in bytes.
Todo:
Handle 4-byte surrogate pair representation
#define oscl_isdigit (c) ((c) >= '0' && (c) <= '9')
#define OSCLTICKCOUNT_MAX_TICKS 0xffffffff
Typedef Documentation
typedef void(* BufferFreeFuncPtr)(void *)
typedef uint32 MediaTimestamp
typedef WStrPtrLen OSCL_TStrPtrLen
typedef OsclAny* OsclComponentFactory
OsclComponentFactory is an opaque pointer.
typedef StrCSumPtrLen StrCSumPtrLen
same as StrPtrLen, but includes checksum field and method to speed up querying
typedef struct StrPtrLen StrPtrLen
This data structure encapsulates a set of functions used to perform.
standard string operations. It should be used for null-terminated constant (non-modifiable) strings of char type.
typedef struct WStrPtrLen WStrPtrLen
This data structure encapsulates a set of functions used to perform.
standard string operations. It should be used for null-terminated constant strings (non-modifiable) of wchar type.
Enumeration Type Documentation
enum TOSCL_StringOp
Conversion operations for OSCL_String classes
Enumerator:
EOSCL_StringOp_CompressASCII
EOSCL_StringOp_UTF16ToUTF8
enum TOSCL_wStringOp
Conversion operations for OSCL_wString classes
Enumerator:
EOSCL_wStringOp_ExpandASCII
EOSCL_wStringOp_UTF8ToUTF16
Function Documentation
OSCL_IMPORT_REF int extract_string (const char * start, const char * end, char * outstring, int maxsize)
OSCL_IMPORT_REF int extract_string (const char * in_ptr, char * outstring, int maxsize)
template<uint32 MaxBufSize> const OSCL_wStackString< MaxBufSize >::chartype * OSCL_wStackString< MaxBufSize >::get_cstr () const [inline, virtual, inherited]
Implements OSCL_wString.
References CStackRep::buffer.
Referenced by OSCL_wStackString< MaxBufSize >::set().
template<uint32 MaxBufSize> const OSCL_StackString< MaxBufSize >::chartype * OSCL_StackString< MaxBufSize >::get_cstr () const [inline, virtual, inherited]
This function returns the C-style string for read access.
Implements OSCL_String.
References CStackRep::buffer.
Referenced by OSCL_StackString< MaxBufSize >::set().
template<class Alloc > const OSCL_wHeapString< Alloc >::chartype * OSCL_wHeapString< Alloc >::get_cstr () const [inline, virtual, inherited]
Implements OSCL_wString.
References CHeapRep::buffer, and NULL.
Referenced by OSCL_wHeapString< Alloc >::set().
template<class Alloc > const OSCL_HeapString< Alloc >::chartype * OSCL_HeapString< Alloc >::get_cstr () const [inline, virtual, inherited]
This function returns the C-style string for read access.
Implements OSCL_String.
References CHeapRep::buffer, and NULL.
Referenced by OSCL_HeapString< Alloc >::set().
template<uint32 MaxBufSize> uint32 OSCL_wStackString< MaxBufSize >::get_maxsize () const [inline, virtual, inherited]
Implements OSCL_wString.
References CStackRep::maxsize.
template<uint32 MaxBufSize> uint32 OSCL_StackString< MaxBufSize >::get_maxsize () const [inline, virtual, inherited]
This function returns the maximum available storage size, not including null terminator. The maximum size may be larger than the current string size.
Implements OSCL_String.
References CStackRep::maxsize.
template<class Alloc > uint32 OSCL_wHeapString< Alloc >::get_maxsize () const [inline, virtual, inherited]
Implements OSCL_wString.
References CHeapRep::maxsize.
template<class Alloc > uint32 OSCL_HeapString< Alloc >::get_maxsize () const [inline, virtual, inherited]
This function returns the maximum available storage size, not including null terminator. The maximum size may be larger than the current string size.
Implements OSCL_String.
References CHeapRep::maxsize.
template<uint32 MaxBufSize> uint32 OSCL_wStackString< MaxBufSize >::get_size () const [inline, virtual, inherited]
Implements OSCL_wString.
References CStackRep::size.
template<uint32 MaxBufSize> uint32 OSCL_StackString< MaxBufSize >::get_size () const [inline, virtual, inherited]
Pure virtuals from OSCL_String
Implements OSCL_String.
References CStackRep::size.
template<class Alloc > uint32 OSCL_wHeapString< Alloc >::get_size () const [inline, virtual, inherited]
Implements OSCL_wString.
References CHeapRep::size.
template<class Alloc > uint32 OSCL_HeapString< Alloc >::get_size () const [inline, virtual, inherited]
Pure virtuals from OSCL_String
Implements OSCL_String.
References CHeapRep::size.
template<uint32 MaxBufSize> OSCL_wStackString< MaxBufSize >::chartype * OSCL_wStackString< MaxBufSize >::get_str () const [inline, virtual, inherited]
Implements OSCL_wString.
References CStackRep::buffer.
template<uint32 MaxBufSize> OSCL_StackString< MaxBufSize >::chartype * OSCL_StackString< MaxBufSize >::get_str () const [inline, virtual, inherited]
This function returns the C-style string for write access. If the string is not writable it returns NULL.
Implements OSCL_String.
References CStackRep::buffer.
template<class Alloc > OSCL_wHeapString< Alloc >::chartype * OSCL_wHeapString< Alloc >::get_str () const [inline, virtual, inherited]
Implements OSCL_wString.
References CHeapRep::buffer, and NULL.
template<class Alloc > OSCL_HeapString< Alloc >::chartype * OSCL_HeapString< Alloc >::get_str () const [inline, virtual, inherited]
This function returns the C-style string for write access. If the string is not writable it returns NULL.
Implements OSCL_String.
References CHeapRep::buffer, and NULL.
template<class ChainClass , uint32 max_frags> BufferState * BufFragGroup< ChainClass, max_frags >::GetBufferState (const int32 idx) [inline, inherited]
References BufFragGroup< ChainClass, max_frags >::buffer_states, NULL, and BufFragGroup< ChainClass, max_frags >::num_fragments.
template<class ChainClass , uint32 max_frags> BufferFragment * BufFragGroup< ChainClass, max_frags >::GetFragment (const int32 idx) [inline, inherited]
References BufFragGroup< ChainClass, max_frags >::fragments, NULL, and BufFragGroup< ChainClass, max_frags >::num_fragments.
template<uint32 MaxBufSize> OSCL_wStackString< MaxBufSize > & OSCL_wStackString< MaxBufSize >::operator= (const chartype * cstr) [inline, inherited]
Reimplemented from OSCL_wString.
References OSCL_wString::set_rep().
template<uint32 MaxBufSize> OSCL_StackString< MaxBufSize > & OSCL_StackString< MaxBufSize >::operator= (const chartype * cstr) [inline, inherited]
Assignment operator
Parameters:
null-terminated string
Reimplemented from OSCL_String.
References OSCL_wString::set_rep().
template<uint32 MaxBufSize> OSCL_wStackString< MaxBufSize > & OSCL_wStackString< MaxBufSize >::operator= (const OSCL_wString & src) [inline, inherited]
Reimplemented from OSCL_wString.
References OSCL_wString::set_rep().
template<uint32 MaxBufSize> OSCL_StackString< MaxBufSize > & OSCL_StackString< MaxBufSize >::operator= (const OSCL_String & src) [inline, inherited]
Assignment operator
Reimplemented from OSCL_String.
References OSCL_wString::set_rep().
template<uint32 MaxBufSize> OSCL_wStackString< MaxBufSize > & OSCL_wStackString< MaxBufSize >::operator= (const OSCL_wStackString< MaxBufSize > & src) [inline, inherited]
References OSCL_wString::set_rep().
template<uint32 MaxBufSize> OSCL_StackString< MaxBufSize > & OSCL_StackString< MaxBufSize >::operator= (const OSCL_StackString< MaxBufSize > & src) [inline, inherited]
Assignment operators
References OSCL_wString::set_rep().
template<class Alloc > OSCL_wHeapString< Alloc > & OSCL_wHeapString< Alloc >::operator= (const chartype * cstr) [inline, inherited]
Reimplemented from OSCL_wString.
References OSCL_wString::set_rep().
template<class Alloc > OSCL_HeapString< Alloc > & OSCL_HeapString< Alloc >::operator= (const chartype * cstr) [inline, inherited]
Assignment operator
Parameters:
null-terminated string
Reimplemented from OSCL_String.
References OSCL_wString::set_rep().
template<class Alloc > OSCL_wHeapString< Alloc > & OSCL_wHeapString< Alloc >::operator= (const OSCL_wString & src) [inline, inherited]
Reimplemented from OSCL_wString.
References OSCL_wString::set_rep().
template<class Alloc > OSCL_HeapString< Alloc > & OSCL_HeapString< Alloc >::operator= (const OSCL_String & src) [inline, inherited]
Assignment operator
Reimplemented from OSCL_String.
References OSCL_wString::set_rep().
template<class Alloc > OSCL_wHeapString< Alloc > & OSCL_wHeapString< Alloc >::operator= (const OSCL_wHeapString< Alloc > & src) [inline, inherited]
References CHeapRep::assign(), and OSCL_wString::set_rep().
template<class Alloc > OSCL_HeapString< Alloc > & OSCL_HeapString< Alloc >::operator= (const OSCL_HeapString< Alloc > & src) [inline, inherited]
Assignment operators
References CHeapRep::assign(), and OSCL_wString::set_rep().
OSCL_IMPORT_REF int oscl_abs (int aVal)
OSCL_COND_IMPORT_REF double oscl_asin (double value)
Calculates the arc since of a number
Parameters:
value source value
OSCL_COND_IMPORT_REF double oscl_atan (double value)
Calculates the arc tangent of a number
Parameters:
value source value
OSCL_COND_IMPORT_REF double oscl_cos (double value)
Calculates the cosine of a number
Parameters:
value source value
OSCL_COND_IMPORT_REF double oscl_exp (double value)
Calculates the exponential of e for a number
Parameters:
value source value
OSCL_COND_IMPORT_REF double oscl_floor (double value)
Calculates the floor of a number
Parameters:
value source value
template<class Alloc > OSCL_HeapString< Alloc >::OSCL_HeapString (const OSCL_String & src) [inline, inherited]
References OSCL_wString::set_rep().
template<class Alloc > OSCL_HeapString< Alloc >::OSCL_HeapString (const OSCL_HeapString< Alloc > & src) [inline, inherited]
Creates a heap string that contains a copy of the input string.
Parameters:
src,: input string.
References CHeapRep::assign(), and OSCL_wString::set_rep().
template<class Alloc > OSCL_HeapString< Alloc >::OSCL_HeapString (const chartype * buf, uint32 length) [inline, inherited]
Creates a heap string that contains a copy of the input string or character array.
Parameters:
src,: character array, not necessarily null-terminated.
length,: number of characters to copy.
template<class Alloc > OSCL_HeapString< Alloc >::OSCL_HeapString (const chartype * cstr) [inline, inherited]
Creates a heap string that contains a copy of the input string.
Parameters:
cp,: null-terminated string.
References OSCL_wString::set_rep().
template<class Alloc > OSCL_HeapString< Alloc >::OSCL_HeapString () [inline, inherited]
The default constructor creates an empty string.
References NULL, and OSCL_wString::set_rep().
OSCL_COND_IMPORT_REF double oscl_log (double value)
Calculates the natural log of a number
Parameters:
value source value
OSCL_COND_IMPORT_REF double oscl_log10 (double value)
Calculates tthe logarithm to base 10 of a number
Parameters:
value source value
OSCL_COND_IMPORT_REF double oscl_pow (double x, double y)
Calculates the value of x to the power of y
Parameters:
x base value
y power
OSCL_COND_IMPORT_REF double oscl_sin (double value)
Calculates the sine of a number
Parameters:
value source value
OSCL_IMPORT_REF int32 oscl_snprintf (oscl_wchar * str, uint32 count, const oscl_wchar * fmt, ...)
OSCL_IMPORT_REF int32 oscl_snprintf (char * str, uint32 count, const char * fmt, ...)
OSCL_COND_IMPORT_REF double oscl_sqrt (double value)
Calculates the square root of a number
Parameters:
value source value
template<uint32 MaxBufSize> OSCL_StackString< MaxBufSize >::OSCL_StackString (const OSCL_String & src) [inline, inherited]
References OSCL_wString::set_rep().
template<uint32 MaxBufSize> OSCL_StackString< MaxBufSize >::OSCL_StackString (const OSCL_StackString< MaxBufSize > & src) [inline, inherited]
Creates an OSCL_StackString with a copy of the input string. The string may be truncated to fit the available storage.
Parameters:
src,: input string.
References OSCL_wString::set_rep().
template<uint32 MaxBufSize> OSCL_StackString< MaxBufSize >::OSCL_StackString (const chartype * buf, uint32 length) [inline, inherited]
Creates an OSCL_StackString with a copy of the input string. The string may be truncated to fit the available storage.
Parameters:
src,: a character array, not necessarily null-terminated.
length,: the number of characters to copy.
template<uint32 MaxBufSize> OSCL_StackString< MaxBufSize >::OSCL_StackString (const chartype * cstr) [inline, inherited]
Creates an OSCL_StackString with a copy of the input string. The string may be truncated to fit the available storage.
Parameters:
cp,: a null-terminated string.
References OSCL_wString::set_rep().
template<uint32 MaxBufSize> OSCL_StackString< MaxBufSize >::OSCL_StackString () [inline, inherited]
Creates an OSCL_StackString initialized with an empty string.
References NULL, and OSCL_wString::set_rep().
OSCL_IMPORT_REF int32 oscl_str_escape_xml (const char * str_buf_in, char * str_buf_out, uint32 max_out_buf_bytes, uint32 max_bytes = 0, uint32 * num_bytes_written = NULL)
Escape any of the following special characters in the string Special ASCII characters: &, <, >, ', ".
The function scans the string and replaces each special character with its corresponding escape sequence. It stops at the first NULL character, the max_byte value.
Parameters:
str_buf_in Ptr to an input string
str_buf_out Ptr to an output buffer which stores the modified string
max_out_buf_bytes The size of str_buf_out.
max_bytes The maximum number of bytes to read (a zero value means read to the first NULL character). It is the length of str_buf_in.
num_bytes_written Number of bytes written in the output buffer, str_buf_out
Returns:
It returns the number of bytes in the str_buf_outring if succeeded. It returns negative number if failed, and its absolute value indicates the total number bytes written to the output buffer, str_buf_out, if str_buf_out != null.
OSCL_IMPORT_REF bool oscl_str_is_valid_utf8 (const uint8 * str_buf, uint32 & num_valid_characters, uint32 max_bytes = 0, uint32 max_char_2_valid = 0, uint32 * num_byte_4_char = NULL)
Check if the input string contains any illegal UTF-8 character. The function scans the string and validate that each character is a valid utf-8. It stops at the first NULL character, invalid character or the max_byte value. The string is valid if and only if every character is a valid utf-8 character and the scanning stopped on a character boundary.
UTF-8 String Manipualation
These routines operate on UTF-8 character string.
Parameters:
str_buf Ptr to an input string, which may not terminate with null, to be checked
num_valid_chars This is an output parameter which is the number of valid utf-8 characters actually read.
max_bytes The maximum number of bytes to read (a zero value means read to the first NULL character).
max_char_2_valid This is an input parameter. Specify the number of utf-8 characters the caller wants to validate.
num_byte_4_char This is an output parameter. The number of bytes used by the max_char characters
Returns:
True if the string is valid and false otherwise.
OSCL_IMPORT_REF bool oscl_str_need_escape_xml (const char * str_buf, uint32 & num_escape_bytes, uint32 max_bytes = 0)
Check if the input string contains any special ASCII character like &, <, >, ', ". The function scans the string and check if each character is a special character. It stops at the first NULL character (if max_bytes = 0), or the max_byte value.
XML String Manipualation
These routines handle the special characters, which needs to be escaped, for xml document.
Parameters:
str_buf Ptr to an input string, which may not terminate with null, to be checked
num_escape_bytes This is an output parameter which is the number of bytes needed to hold the result string. Value 0 indicates that there is no special character found. If max_bytes = 0, the return value does not include the null character.
max_bytes The maximum number of bytes to read (a zero value means read to the first NULL character).
Returns:
True if the function succeeds, and num_escape_bytes = 0 means that no special character is found, num_escape_bytes >0 means the number of bytes of the result string. False if there is any error occurred.
OSCL_IMPORT_REF int32 oscl_str_truncate_utf8 (uint8 * str_buf, uint32 max_char, uint32 max_bytes = 0)
Truncates the UTF-8 string upto the required size.
The function will modify the str_buf so that it contains AT MOST len valid utf-8 characters. If a NULL character is found before reading len utf-8 characters, then the function does not modify the string and simply returns the number of characters. If an invalid character is found, then it will insert a NULL character after the last valid character and return the length. Otherwise, it will insert a NULL character after len valid utf-8 characters and return the length.
Parameters:
str_buf Ptr to an input string which may not terminate with null
max_char The max number of the UTF-8 CHARACTERS
max_bytes The maximum number of bytes to read (a zero value means read to the first NULL character).
Returns:
It returns the length of the truncated string in utf-8 characters.
OSCL_IMPORT_REF bool oscl_str_unescape_uri (const OSCL_String & oscl_str_in, OSCL_String & oscl_str_out, uint32 & out_buf_len)
unescape any of the special escape sequence in the uri string
The function scans the string and replaces each escape sequence with its corresponding character. It stops at the first null character, or the max_byte value. It returns false if the string contains any illegal escape sequence or the output buffer is not big enough. The out_buf_len value indicates the needed buffer length or the index of the byte that causes the error respectively.
Parameters:
oscl_str_in Ptr to an input OSCL_String
oscl_str_out Ptr to an output OSCL_String which stores the modified string
out_buf_len The length of the result string (not including the null character)
Returns:
It returns true if succeeds, otherwise false.
OSCL_IMPORT_REF bool oscl_str_unescape_uri (const char * str_buf_in, char * str_buf_out, uint32 max_out_buf_bytes, uint32 max_bytes, uint32 & out_buf_len)
unescape any of the special escape sequence in the uri string
URI String Manipualation
These routines handle all of the special escape sequences in the URI.
The function scans the string and replaces each escape sequence with its corresponding character. It stops at the first null character, or the max_byte value. It returns false if the string contains any illegal escape sequence or the output buffer is not big enough. The out_buf_len value indicates the needed buffer length or the index of the byte that causes the error respectively.
Parameters:
str_buf_in Ptr to an input string
str_buf_out Ptr to an output buffer which stores the modified string
max_out_buf_bytes The size of str_buf_out.
max_bytes The maximum number of bytes to read. It is the length of str_buf_in.
out_buf_len The length of the result string (not including the null character)
Returns:
It returns true if succeeds, otherwise false.
OSCL_COND_IMPORT_REF double oscl_tan (double value)
Calculates the tangential of a number
Parameters:
value source value
OSCL_IMPORT_REF int32 oscl_UnicodeToUTF8 (const oscl_wchar * input, int32 inLength, char * output, int32 outLength)
Convert UTF-16 Unicode string to UTF8 byte sequence.
The function converts Unicode string to UTF8 byte sequence. The length of input Unicode string is specified. It stops at two conditions: (A) Whole input Unicode string is successfully converted. (B) Destination buferr is not enough for output. In case of (A), it adds a terminated '' at the end of the output UTF8 byte sequence. and returns length of the output UTF8 byte sequence(without counting terminated ''). In case of (B), it converts as much as possible to the output buffer and adds a terminated '' at the end of the output UTF8 byte sequence"(no '\0' added if outLength is less than or equal to 0, return 0)", and returns 0. Please note that Unicode character exceeding U+FFFF are not supported.
Parameters:
input Ptr to an input Unicode string. '' termanation is not neccesary.
inLength The length of the input Unicode string, without counting terminated ''(if any).
output Ptr to an output buffer which output UTF8 byte sequence is written in.
outLength The size of output buffer, also the maximum number of char could be written in.
Returns:
length of output (excludes '') : completely converts all input string and appends '' to output; 0 : insufficient buffer or error in conversion
OSCL_IMPORT_REF int32 oscl_UTF8ToUnicode (const char * input, int32 inLength, oscl_wchar * output, int32 outLength)
Convert UTF8 byte sequence to Unicode UTF-16 string.
The function converts UTF8 byte sequence (or ASCII sequence) to UTF-16 string. The length of input UTF8 byte sequence is specified. It stops at two conditions: (A) Whole input UTF8 byte sequence is successfully converted. (B) Output buferr is not enough for output, or parse error. In case of (A), it adds a terminated '' at the end of the output Unicode string, and returns length of the output Unicode string(without counting terminated ''). In case of (B), it converts as much as possible to the output buffer and adds a terminated '' at the end of the output Unicode string"(no '\0' added if outLength is less than or equal to 0, return 0)", and returns 0. Please note that Unicode character exceeding U+FFFF are not supported.
Parameters:
input Ptr to an input UTF8 byte sequence. '' termanation is not neccesary.
inLength The length of the input UTF8 byte sequence, without counting terminated ''(if any).
output Ptr to an output buffer which output Unicode string is written in.
outLength The size of output buffer, also the maximum number of oscl_wchar could be written in.
Returns:
Length of output (excludes '') : completely converts all input string and appends '' to output; 0 : insufficient buffer or error in conversion
OSCL_IMPORT_REF int32 oscl_vsnprintf (oscl_wchar * str, uint32 count, const oscl_wchar * fmt, va_list args)
OSCL_IMPORT_REF int32 oscl_vsnprintf (char * str, uint32 count, const char * fmt, va_list args)
template<class Alloc > OSCL_wHeapString< Alloc >::OSCL_wHeapString (const OSCL_wString & src) [inline, inherited]
References OSCL_wString::set_rep().
template<class Alloc > OSCL_wHeapString< Alloc >::OSCL_wHeapString (const OSCL_wHeapString< Alloc > & src) [inline, inherited]
References CHeapRep::assign(), and OSCL_wString::set_rep().
template<class Alloc > OSCL_wHeapString< Alloc >::OSCL_wHeapString (const chartype * buf, uint32 length) [inline, inherited]
template<class Alloc > OSCL_wHeapString< Alloc >::OSCL_wHeapString (const chartype * cstr) [inline, inherited]
References OSCL_wString::set_rep().
template<class Alloc > OSCL_wHeapString< Alloc >::OSCL_wHeapString () [inline, inherited]
References NULL, and OSCL_wString::set_rep().
template<uint32 MaxBufSize> OSCL_wStackString< MaxBufSize >::OSCL_wStackString (const OSCL_wString & src) [inline, inherited]
References OSCL_wString::set_rep().
template<uint32 MaxBufSize> OSCL_wStackString< MaxBufSize >::OSCL_wStackString (const OSCL_wStackString< MaxBufSize > & src) [inline, inherited]
References OSCL_wString::set_rep().
template<uint32 MaxBufSize> OSCL_wStackString< MaxBufSize >::OSCL_wStackString (const chartype * buf, uint32 length) [inline, inherited]
template<uint32 MaxBufSize> OSCL_wStackString< MaxBufSize >::OSCL_wStackString (const chartype * cstr) [inline, inherited]
References OSCL_wString::set_rep().
template<uint32 MaxBufSize> OSCL_wStackString< MaxBufSize >::OSCL_wStackString () [inline, inherited]
References NULL, and OSCL_wString::set_rep().
OSCL_IMPORT_REF bool PV_atof (const char * buf, int length, OsclFloat & value)
OSCL_IMPORT_REF bool PV_atof (const char * buf, OsclFloat & value)
OSCL_IMPORT_REF bool PV_atoi (const char * buf, const char new_format, int length, uint64 & value)
OSCL_IMPORT_REF bool PV_atoi (const char * buf, const char new_format, int length, uint32 & value)
OSCL_IMPORT_REF bool PV_atoi (const char * buf, const char new_format, uint32 & value)
template<uint32 MaxBufSize> void OSCL_wStackString< MaxBufSize >::set (const other_chartype * buf, uint32 length, optype op) [inline, inherited]
References NULL, OSCL_wString::setrep_to_wide_char(), and CStackRep::size.
template<uint32 MaxBufSize> void OSCL_StackString< MaxBufSize >::set (const other_chartype * buf, uint32 length, optype op) [inline, inherited]
Set the contents of this string to a new string or character array, with conversion operation.
Parameters:
buf,: string or character array.
length,: number of characters to copy.
op,: conversion operation to apply
References NULL, OSCL_String::setrep_to_char(), and CStackRep::size.
template<uint32 MaxBufSize> void OSCL_wStackString< MaxBufSize >::set (const other_chartype * buf, optype op) [inline, inherited]
References NULL, oscl_strlen(), OSCL_wString::setrep_to_wide_char(), and CStackRep::size.
template<uint32 MaxBufSize> void OSCL_StackString< MaxBufSize >::set (const other_chartype * buf, optype op) [inline, inherited]
Set the contents of this string to a new string, with conversion operation.
Parameters:
buf,: NULL-terminated wide string.
op,: conversion operation to apply
References NULL, oscl_strlen(), OSCL_String::setrep_to_char(), and CStackRep::size.
template<uint32 MaxBufSize> void OSCL_wStackString< MaxBufSize >::set (const chartype * buf, uint32 length) [inline, inherited]
References OSCL_wStackString< MaxBufSize >::get_cstr(), oscl_strlen(), CStackRep::set(), and CStackRep::size.
template<uint32 MaxBufSize> void OSCL_StackString< MaxBufSize >::set (const chartype * buf, uint32 length) [inline, inherited]
Set the contents of this string to a new string or character array.
Parameters:
buf,: string or character array.
length,: number of characters to copy.
References OSCL_StackString< MaxBufSize >::get_cstr(), oscl_strlen(), CStackRep::set(), and CStackRep::size.
template<class Alloc > void OSCL_wHeapString< Alloc >::set (const other_chartype * buf, uint32 length, optype op) [inline, inherited]
References OSCL_wString::setrep_to_wide_char(), and CHeapRep::size.
template<class Alloc > void OSCL_HeapString< Alloc >::set (const other_chartype * buf, uint32 length, optype op) [inline, inherited]
Set the contents of this string to a new string or character array, with conversion operation.
Parameters:
buf,: string or character array.
length,: number of characters to copy.
op,: conversion operation to apply
References OSCL_String::setrep_to_char(), and CHeapRep::size.
template<class Alloc > void OSCL_wHeapString< Alloc >::set (const other_chartype * buf, optype op) [inline, inherited]
References oscl_strlen(), OSCL_wString::setrep_to_wide_char(), and CHeapRep::size.
template<class Alloc > void OSCL_HeapString< Alloc >::set (const other_chartype * buf, optype op) [inline, inherited]
Set the contents of this string to a new string, with conversion operation.
Parameters:
buf,: NULL-terminated wide string.
op,: conversion operation to apply
References oscl_strlen(), OSCL_String::setrep_to_char(), and CHeapRep::size.
template<class Alloc > void OSCL_wHeapString< Alloc >::set (const chartype * buf, uint32 length) [inline, inherited]
References OSCL_wHeapString< Alloc >::get_cstr(), oscl_strlen(), OSCL_wString::set_rep(), and CHeapRep::size.
template<class Alloc > void OSCL_HeapString< Alloc >::set (const chartype * buf, uint32 length) [inline, inherited]
Set the contents of this string to a new string or character array.
Parameters:
buf,: string or character array.
length,: number of characters to copy.
References OSCL_HeapString< Alloc >::get_cstr(), oscl_strlen(), OSCL_wString::set_rep(), and CHeapRep::size.
OSCL_IMPORT_REF const char* skip_to_line_term (const char * start_ptr, const char * end_ptr)
OSCL_IMPORT_REF const char* skip_to_whitespace (const char * start, const char * end)
OSCL_IMPORT_REF const char* skip_whitespace (const char * start, const char * end)
OSCL_IMPORT_REF char* skip_whitespace (char * ptr)
OSCL_IMPORT_REF const char* skip_whitespace (const char * ptr)
OSCL_IMPORT_REF const char* skip_whitespace_and_line_term (const char * start, const char * end)
template<class Alloc > OSCL_HeapString< Alloc >::~OSCL_HeapString () [inline, inherited]
References CHeapRep::remove_ref().
template<uint32 MaxBufSize> OSCL_StackString< MaxBufSize >::~OSCL_StackString () [inline, inherited]
template<class Alloc > OSCL_wHeapString< Alloc >::~OSCL_wHeapString () [inline, inherited]
References CHeapRep::remove_ref().
template<uint32 MaxBufSize> OSCL_wStackString< MaxBufSize >::~OSCL_wStackString () [inline, inherited]
Variable Documentation
const int32 APPEND_MEDIA_AT_END = -1
const uint8 OSCL_ASCII_CASE_MAGIC_BIT = 0x20
Referenced by WStrPtrLen::isCIEquivalentTo(), and StrPtrLen::isCIPrefixOf().
OSCL API
Posting Version: CORE_9.005.1.1