oscl: OSCL Memory
OSCL Memory
Data Structures
class OsclMem
class OsclAuditCB
class OsclMemAllocator
class OsclMemBasicAllocator
class OsclMemAllocDestructDealloc< T >
class OsclMemBasicAllocDestructDealloc< T >
class OsclMemGlobalAuditObject
class HeapBase
struct MM_Stats_t
struct MM_FailInsertParam
class OsclMemStatsNode
struct MM_Stats_CB
struct MM_AllocQueryInfo
struct MM_AllocInfo
struct MM_AllocNode
struct MM_AuditOverheadStats
class MM_Audit_Imp
class OsclMemAudit
struct MM_AllocBlockHdr
struct MM_AllocBlockFence
class OSCLMemAutoPtr< T, _Allocator >
The oscl_auto_ptr class is a template class that defines a pointer like object intended to be assigned an address obtanined (directly or or indirectly) by new. When the oscl_auto_ptr expires, its destructor uses delete to free the memory.
class OsclMemPoolFixedChunkAllocatorObserver
class OsclMemPoolFixedChunkAllocator
class OsclMemPoolResizableAllocatorObserver
class OsclMemPoolResizableAllocatorMemoryObserver
class OsclMemPoolResizableAllocator
class allocator
Files
file oscl_mem_basic_functions.h
This file contains prototypes for the basic memory functions.
file oscl_mem.h
This file contains basic memory definitions for common use across platforms.
file oscl_mem_audit.h
This file contains the definition and partial implementation of MM_Audit class.
file oscl_mem_audit_internals.h
This file contains the internal definitions for the mem audit library.
file oscl_mem_auto_ptr.h
This file defines the oscl_mem_auto_ptr template class. This class is used to avoid any potential memory leaks that may arise while returning from methods in case of error.
file oscl_mem_mempool.h
This file contains the definition of memory pool allocators.
Defines
#define OSCL_DISABLE_WARNING_TRUNCATE_DEBUG_MESSAGE
#define OSCL_DISABLE_WARNING_TRUNCATE_DEBUG_MESSAGE
#define OSCL_CLEANUP_BASE_CLASS(T) _OSCL_CLEANUP_BASE_CLASS(T)
#define OSCL_ALLOC_NEW(T_allocator, T, params) new(T_allocator.allocate(1)) T params
#define OSCL_TRAP_ALLOC_NEW(T_ptr, T_allocator, T, params) _OSCL_TRAP_NEW(T_allocator.allocate(1),T_allocator.deallocate,T_ptr,T,params)
#define OSCL_ALLOC_DELETE(ptr, T_allocator, T)
#define OSCL_MALLOC(count) _oscl_malloc(count)
#define oscl_malloc(a) OSCL_MALLOC(a)
#define OSCL_DEFAULT_MALLOC(x) OSCL_MALLOC(x)
#define OSCL_AUDIT_MALLOC(auditCB, count) _oscl_malloc(count)
#define OSCL_CALLOC(num, size) _oscl_calloc(num,size)
#define oscl_calloc(a, b) OSCL_CALLOC(a,b)
#define OSCL_AUDIT_CALLOC(auditCB, num, size) _oscl_calloc(num,size)
#define OSCL_REALLOC(ptr, new_size) _oscl_realloc(ptr,new_size)
#define oscl_realloc(a, b) OSCL_REALLOC(a,b)
#define OSCL_AUDIT_REALLOC(auditCB, ptr, new_size) _oscl_realloc(ptr,new_size)
#define OSCL_FREE(ptr) _oscl_free(ptr)
#define oscl_free(x) OSCL_FREE(x)
#define OSCL_DEFAULT_FREE(x) OSCL_FREE(x)
#define OSCL_NEW(T, params) new T params
#define OSCL_PLACEMENT_NEW(ptr, constructor) new(ptr) constructor
#define OSCL_TRAP_NEW(T_ptr, T, params) _OSCL_TRAP_NEW(_oscl_default_new(sizeof(T)),_oscl_free,T_ptr,T,params)
#define OSCL_AUDIT_NEW(auditCB, T, params) new(_oscl_default_new(sizeof(T))) T params
#define OSCL_TRAP_AUDIT_NEW(T_ptr, auditCB, T, params) _OSCL_TRAP_NEW(_oscl_default_new(sizeof(T)),_oscl_free,T_ptr,T,params)
#define OSCL_DELETE(ptr)
#define OSCL_AUDIT_ARRAY_NEW(auditCB, T, count) new(_oscl_default_new(sizeof(T)*(count))) T
#define OSCL_ARRAY_NEW(T, count) new T[count]
#define OSCL_ARRAY_DELETE(ptr) delete [] ptr
#define _OSCL_TRAP_NEW(exp, freeFunc, T_ptr, T, params)
#define _OSCL_CLEANUP_BASE_CLASS(T) this->T::~T()
#define OSCL_DISABLE_WARNING_TRUNCATE_DEBUG_MESSAGE
#define MM_ALLOC_MAX_QUERY_FILENAME_LEN 128
#define MM_ALLOC_MAX_QUERY_TAG_LEN 64
#define MM_AUDIT_VALIDATE_BLOCK 1
#define MM_AUDIT_PREFILL_FLAG 0x1
#define MM_AUDIT_POSTFILL_FLAG 0x2
#define MM_AUDIT_VALIDATE_ALL_HEAP_FLAG 0x4
#define MM_AUDIT_VALIDATE_ON_FREE_FLAG 0x8
#define MM_AUDIT_ALLOC_NODE_ENABLE_FLAG 0x10
#define MM_AUDIT_SUPPRESS_FILENAME_FLAG 0x20
#define DEFAULT_MM_AUDIT_MODE 0
#define OSCL_DISABLE_WARNING_TRUNCATE_DEBUG_MESSAGE
#define MM_AUDIT_ALLOC_NODE_SUPPORT 1
#define MM_AUDIT_FENCE_SUPPORT 0
#define MM_AUDIT_INCLUDE_ALL_HEAP_VALIDATION 1
#define MM_AUDIT_FILL_SUPPORT 0
#define MM_AUDIT_FAILURE_SIMULATION_SUPPORT 1
#define FENCE_PATTERN 0xAA
#define MIN_FENCE_SIZE 4
#define MEM_ALIGN_SIZE 8
#define COMPUTE_MEM_ALIGN_SIZE(x, y, z) (y+(((x+y)%z) ? (z - (x+y)%z) : 0))
#define DEFAULT_PREFILL_PATTERN 0x96
#define DEFAULT_POSTFILL_PATTERN 0x5A
#define OSCL_DISABLE_WARNING_TRUNCATE_DEBUG_MESSAGE
#define OSCL_DISABLE_WARNING_RETURN_TYPE_NOT_UDT
Typedefs
typedef OSCLMemAutoPtr< char,
Oscl_TAlloc< char,
OsclMemBasicAllocator > > MMAuditCharAutoPtr
typedef OSCLMemAutoPtr< uint8,
Oscl_TAlloc< uint8,
_OsclBasicAllocator > > MMAuditUint8AutoPtr
typedef OSCLMemAutoPtr
< MM_AllocNode, Oscl_TAlloc
< MM_AllocNode,
OsclMemBasicAllocator > > MM_AllocNodeAutoPtr
typedef OSCLMemAutoPtr
< OsclMemStatsNode,
Oscl_TAlloc< OsclMemStatsNode,
OsclMemBasicAllocator > > MM_StatsNodeTagTreeType
typedef OSCLMemAutoPtr
< OsclMemStatsNode,
Oscl_TAlloc< OsclMemStatsNode,
OsclMemBasicAllocator > > OsclMemStatsNodeAutoPtr
typedef Oscl_TAlloc
< MM_StatsNodeTagTreeType,
OsclMemBasicAllocator > TagTree_Allocator
typedef Oscl_TagTree
< MM_StatsNodeTagTreeType,
TagTree_Allocator > OsclTagTreeType
Functions
OSCL_COND_IMPORT_REF void * _oscl_malloc (int32 count)
OSCL_COND_IMPORT_REF void * _oscl_calloc (int32 nelems, int32 size)
OSCL_COND_IMPORT_REF void * _oscl_realloc (void *src, int32 count)
OSCL_COND_IMPORT_REF void _oscl_free (void *src)
OSCL_COND_IMPORT_REF void * oscl_memcpy (void *dest, const void *src, uint32 count)
OSCL_COND_IMPORT_REF void * oscl_memmove (void *dest, const void *src, uint32 count)
OSCL_COND_IMPORT_REF void * oscl_memmove32 (void *dest, const void *src, uint32 count)
OSCL_COND_IMPORT_REF void * oscl_memset (void *dest, uint8 val, uint32 count)
OSCL_COND_IMPORT_REF int oscl_memcmp (const void *buf1, const void *buf2, uint32 count)
OSCL_COND_IMPORT_REF uint oscl_mem_aligned_size (uint size)
OSCL_IMPORT_REF void OsclMemInit (OsclAuditCB &auditCB)
OSCL_IMPORT_REF void * _oscl_default_new (size_t nBytes)
void * operator new (size_t aSize)
void operator delete (void *aPtr)
void * operator new[] (size_t aSize)
void operator delete[] (void *aPtr)
Variables
static const uint32 MM_AllocBlockHdr::ALLOC_NODE_FLAG = 0x80000000
Define Documentation
#define _OSCL_CLEANUP_BASE_CLASS (T) this->T::~T()
This macro is used to cleanup the base class in a derived-class constructor just before a leave occurs.
Parameters:
T,: base class name.
#define _OSCL_TRAP_NEW (exp, freeFunc, T_ptr, T, params)
Value:
{\
    int32 __err;\
    OsclAny*__ptr=exp;\
    OSCL_TRY(__err,T_ptr=new(__ptr) T params;);\
    if(__err){\
        freeFunc(__ptr);\
        T_ptr=NULL;\
        OsclError::Leave(__err);\
    }\
}
Internal-use macro to catch leaves in constructors. If the constructor leaves, this will free the memory before allowing the leave to propagate to the next level. It is the constructor's responsibility to cleanup any memory in the partially constructed object before leaving. This cleanup may include cleaning up the base class using the OSCL_CLEANUP_BASE_CLASS macro.
Parameters:
exp,: expression to allocate memory.
Tptr:variable to hold result.
T,: type
params,: constructor arg list
freeFunc,: delete or free function.
#define COMPUTE_MEM_ALIGN_SIZE (x, y, z) (y+(((x+y)%z) ? (z - (x+y)%z) : 0))
#define DEFAULT_MM_AUDIT_MODE 0
#define DEFAULT_POSTFILL_PATTERN 0x5A
#define DEFAULT_PREFILL_PATTERN 0x96
#define FENCE_PATTERN 0xAA
Referenced by MM_AllocBlockFence::check_fence(), and MM_AllocBlockFence::fill_fence().
#define MEM_ALIGN_SIZE 8
#define MIN_FENCE_SIZE 4
#define MM_ALLOC_MAX_QUERY_FILENAME_LEN 128
#define MM_ALLOC_MAX_QUERY_TAG_LEN 64
#define MM_AUDIT_ALLOC_NODE_ENABLE_FLAG 0x10
#define MM_AUDIT_ALLOC_NODE_SUPPORT 1
#define MM_AUDIT_FAILURE_SIMULATION_SUPPORT 1
#define MM_AUDIT_FENCE_SUPPORT 0
#define MM_AUDIT_FILL_SUPPORT 0
#define MM_AUDIT_INCLUDE_ALL_HEAP_VALIDATION 1
#define MM_AUDIT_POSTFILL_FLAG 0x2
#define MM_AUDIT_PREFILL_FLAG 0x1
#define MM_AUDIT_SUPPRESS_FILENAME_FLAG 0x20
#define MM_AUDIT_VALIDATE_ALL_HEAP_FLAG 0x4
#define MM_AUDIT_VALIDATE_BLOCK 1
#define MM_AUDIT_VALIDATE_ON_FREE_FLAG 0x8
#define OSCL_ALLOC_DELETE (ptr, T_allocator, T)
Value:
{\
  ptr->~T();\
  T_allocator.deallocate(ptr);\
  }
Deletes the object of type T using the given allocator
Parameters:
T_allocator allocator for objects of type T
T type of object to delete
ptr pointer to previously created object
Exceptions:
none,unless thrown by the given allocator
#define OSCL_ALLOC_NEW (T_allocator, T, params) new(T_allocator.allocate(1)) T params
******************************************************* Macros for new/delete with a given allocator/deallocator. Creates an object of type T using the given allocator to acquire the memory needed.
Parameters:
T_allocator allocator for objects of type T, must be an Oscl_TAlloc<T, Allocator>, where Allocator is an Oscl_DefAlloc
T type of object to create
params object initialization parameters
Returns:
pointer to created object
Exceptions:
none,unless thrown by the given allocator
#define OSCL_ARRAY_DELETE (ptr) delete [] ptr
Oscl array delete operator..
Parameters:
ptr pointer to memory block previously allocated with OSCL_ARRAY_NEW
Returns:
void
#define OSCL_ARRAY_NEW (T, count) new T[count]
Oscl array "new" operator. This uses the global memory audit object.
Parameters:
T data type for 'new' operation
count number of elements to create
Returns:
pointer to the newly created object array of type T
Exceptions:
may leave with code = bad alloc
#define OSCL_AUDIT_ARRAY_NEW (auditCB, T, count) new(_oscl_default_new(sizeof(T)*(count))) T
******************************************************* Macros for array new/delete with memory management. These only work for simple array types and cannot be used for class types with constructor/destructors.
Note: some compilers do not support placement array new operator, so these macros don't use it. Oscl array "new" operator. This uses the input memory audit object.
Parameters:
auditCB input memory management audit object
T data type for 'new' operation
count number of elements to create
Returns:
pointer to the newly created object array of type T
Exceptions:
may leave with code = bad alloc
#define OSCL_AUDIT_CALLOC (auditCB, num, size) _oscl_calloc(num,size)
Allocates a memory block using the specified audit object. The block is initialized to zero.
Parameters:
auditCB input memory management audit object
num number of elements
size number of bytes to allocate for each element
Returns:
a void pointer to the allocated space, or NULL if there is insufficient memory available.
Exceptions:
none
#define OSCL_AUDIT_MALLOC (auditCB, count) _oscl_malloc(count)
Allocates a memory block using the given audit object.
Parameters:
auditCB input memory management audit object
count number of bytes to allocate
Returns:
a void pointer to the allocated space, or NULL if there is insufficient memory available.
Exceptions:
none
#define OSCL_AUDIT_NEW (auditCB, T, params) new(_oscl_default_new(sizeof(T))) T params
Oscl "new" operator. This uses the specified memory audit object.
Parameters:
auditCB input memory management audit object
T data type for 'new' operation
params object initialization parameters
Returns:
pointer to the newly created object of type T
Exceptions:
may leave with code = bad alloc
#define OSCL_AUDIT_REALLOC (auditCB, ptr, new_size) _oscl_realloc(ptr,new_size)
Re-Allocates a memory block using the specified audit object.
Parameters:
auditCB input memory management audit object
ptr original memory block
new_size New size of the block
Returns:
a void pointer to the allocated space, or NULL if there is insufficient memory available.
Exceptions:
none
#define oscl_calloc (a, b) OSCL_CALLOC(a,b)
#define OSCL_CALLOC (num, size) _oscl_calloc(num,size)
Allocates a memory block using the memory management's global audit object. The block is initialized to zero.
Parameters:
num number of elements
size number of bytes to allocate for each element
Returns:
a void pointer to the allocated space, or NULL if there is insufficient memory available.
Exceptions:
none
#define OSCL_CLEANUP_BASE_CLASS (T) _OSCL_CLEANUP_BASE_CLASS(T)
Cleans up the base class of a partially-constructed derived class. This macro will call the destructor if necessary, based on the error-handling implementation.
Parameters:
T,: name of the base class.
#define OSCL_DEFAULT_FREE (x) OSCL_FREE(x)
Another back-compatibility definition.
#define OSCL_DEFAULT_MALLOC (x) OSCL_MALLOC(x)
Another back-compatibility definition.
#define OSCL_DELETE (ptr)
Value:
{\
    if(ptr){delete(ptr);}\
}
Oscl "delete" operator.
Parameters:
ptr pointer to memory block previously allocated with OSCL_NEW
Returns:
void
Referenced by OsclBuf::Delete(), OsclBuf::NewL(), MM_AllocNode::~MM_AllocNode(), and OsclMemStatsNode::~OsclMemStatsNode().
#define OSCL_DISABLE_WARNING_RETURN_TYPE_NOT_UDT
#define OSCL_DISABLE_WARNING_TRUNCATE_DEBUG_MESSAGE
#define OSCL_DISABLE_WARNING_TRUNCATE_DEBUG_MESSAGE
#define OSCL_DISABLE_WARNING_TRUNCATE_DEBUG_MESSAGE
#define OSCL_DISABLE_WARNING_TRUNCATE_DEBUG_MESSAGE
Previously this was in oscl_mem_imp.h
#define OSCL_DISABLE_WARNING_TRUNCATE_DEBUG_MESSAGE
Previously this was in oscl_mem_imp.h
#define oscl_free (x) OSCL_FREE(x)
#define OSCL_FREE (ptr) _oscl_free(ptr)
Deallocates or frees a memory block.
Parameters:
ptr pointer to previously allocated memory block using the given audit object
Referenced by OsclMemAllocator::deallocate(), and OsclBuf::Delete().
#define oscl_malloc (a) OSCL_MALLOC(a)
#define OSCL_MALLOC (count) _oscl_malloc(count)
Allocates a memory block using the memory management's global audit object.
Parameters:
count number of bytes to allocate
Returns:
a void pointer to the allocated space, or NULL if there is insufficient memory available.
Exceptions:
none
Referenced by OsclBuf::NewL().
#define OSCL_NEW (T, params) new T params
******************************************************* Macros for new/delete with memory management. Oscl "new" operator. This uses the global memory audit object.
Parameters:
T data type for 'new' operation
params object initialization parameters
Returns:
pointer to the newly created object of type T
Exceptions:
may leave with code = bad alloc
Referenced by OsclBuf::NewL().
#define OSCL_PLACEMENT_NEW (ptr, constructor) new(ptr) constructor
Referenced by OsclTimer< Alloc >::OsclTimer().
#define oscl_realloc (a, b) OSCL_REALLOC(a,b)
#define OSCL_REALLOC (ptr, new_size) _oscl_realloc(ptr,new_size)
Re-Allocates a memory block using the memory management's global audit object.
Parameters:
ptr original memory block
new_size New size of the block
Returns:
a void pointer to the allocated space, or NULL if there is insufficient memory available.
Exceptions:
none
#define OSCL_TRAP_ALLOC_NEW (T_ptr, T_allocator, T, params) _OSCL_TRAP_NEW(T_allocator.allocate(1),T_allocator.deallocate,T_ptr,T,params)
Creates an object of type T using the given allocator to acquire the memory needed. This macro is similar to OSCL_ALLOC_NEW except that it handles constructors that leave. If the constructor leaves, the destructor will be called, and allocated memory will be freed before allowing the leave to propagate to the next level.
Parameters:
T_ptr variable to hold return value-- pointer to new object of type T.
T_allocator allocator for objects of type T, must be an Oscl_TAlloc<T, Allocator>, where Allocator is an Oscl_DefAlloc
T type of object to create
params object initialization parameters
Returns:
pointer to created object
Exceptions:
none,unless thrown by the given allocator
#define OSCL_TRAP_AUDIT_NEW (T_ptr, auditCB, T, params) _OSCL_TRAP_NEW(_oscl_default_new(sizeof(T)),_oscl_free,T_ptr,T,params)
Oscl "new" operator. This uses the specified memory audit object. This macro is similar to OSCL_AUDIT_NEW except that it will handle constructors that leave. If the constructor leaves, the destructor will be called, and allocated memory will be freed before allowing the leave to propagate to the next level.
Parameters:
T_ptr variable to hold return value-- pointer to new object of type T.
auditCB input memory management audit object
T data type for 'new' operation
params object initialization parameters
Returns:
pointer to the newly created object of type T
Exceptions:
may leave with code = bad alloc
#define OSCL_TRAP_NEW (T_ptr, T, params) _OSCL_TRAP_NEW(_oscl_default_new(sizeof(T)),_oscl_free,T_ptr,T,params)
Oscl "new" operator. This uses the global memory audit object. This operator is similar to OSCL_NEW except that it will handle constructors that leave. If the constructor leaves, the destructor will be called, and allocated memory will be freed before allowing the leave to propagate to the next level.
Parameters:
T_ptr variable to hold return value-- pointer to new object of type T.
T data type for 'new' operation
params object initialization parameters
Returns:
pointer to the newly created object of type T
Exceptions:
may leave with code = bad alloc
Typedef Documentation
typedef OSCLMemAutoPtr<MM_AllocNode, Oscl_TAlloc<MM_AllocNode, OsclMemBasicAllocator> > MM_AllocNodeAutoPtr
typedef OSCLMemAutoPtr<OsclMemStatsNode, Oscl_TAlloc<OsclMemStatsNode, OsclMemBasicAllocator> > MM_StatsNodeTagTreeType
typedef OSCLMemAutoPtr<char, Oscl_TAlloc<char, OsclMemBasicAllocator> > MMAuditCharAutoPtr
typedef OSCLMemAutoPtr<uint8, Oscl_TAlloc<uint8, _OsclBasicAllocator> > MMAuditUint8AutoPtr
typedef OSCLMemAutoPtr<OsclMemStatsNode, Oscl_TAlloc<OsclMemStatsNode, OsclMemBasicAllocator> > OsclMemStatsNodeAutoPtr
typedef Oscl_TagTree<MM_StatsNodeTagTreeType, TagTree_Allocator> OsclTagTreeType
typedef Oscl_TAlloc<MM_StatsNodeTagTreeType, OsclMemBasicAllocator> TagTree_Allocator
Function Documentation
OSCL_COND_IMPORT_REF void* _oscl_calloc (int32 nelems, int32 size)
OSCL_IMPORT_REF void* _oscl_default_new (size_t nBytes)
******************************************************* Macros for malloc/free with memory management.
Referenced by HeapBase::operator new(), operator new(), HeapBase::operator new[](), and operator new[]().
OSCL_COND_IMPORT_REF void _oscl_free (void * src)
Referenced by OsclMemBasicAllocator::deallocate(), HeapBase::operator delete(), operator delete(), HeapBase::operator delete[](), and operator delete[]().
OSCL_COND_IMPORT_REF void* _oscl_malloc (int32 count)
Referenced by OsclMemBasicAllocator::allocate(), and OsclMemAllocator::allocate().
OSCL_COND_IMPORT_REF void* _oscl_realloc (void * src, int32 count)
void operator delete (void * aPtr) [inline]
References _oscl_free().
void operator delete[] (void * aPtr) [inline]
References _oscl_free().
void* operator new (size_t aSize) [inline]
References _oscl_default_new().
void* operator new[] (size_t aSize) [inline]
References _oscl_default_new().
OSCL_COND_IMPORT_REF uint oscl_mem_aligned_size (uint size)
Get memory-aligned size of an object.
Parameters:
size size of object
Returns:
memory-aligned size
OSCL_COND_IMPORT_REF int oscl_memcmp (const void * buf1, const void * buf2, uint32 count)
Compare characters in two buffers
Parameters:
buf1 first buffer
buf2 second buffer
count number of bytes to compare
Returns:
<0 buf1 less than buf2 0 buf1 equal to buf2 >0 buf1 greater than buf2
OSCL_COND_IMPORT_REF void* oscl_memcpy (void * dest, const void * src, uint32 count)
Copies characters between buffers The oscl_memcpy function copies count bytes of src to dest. If the source and destination overlap, this function does not ensure that the original source bytes in the overlapping region are copied before being overwritten. Use oscl_memmove to handle overlapping regions
Parameters:
dest new buffer
src buffer to copy
count number of bytes to copy
Returns:
the value of dest
Referenced by MediaData< ChainClass, max_frags, local_bufsize >::AddLocalFragment(), OsclUuid::operator=(), and OsclUuid::OsclUuid().
OSCL_COND_IMPORT_REF void* oscl_memmove (void * dest, const void * src, uint32 count)
Moves chars from one buffer to another The memmove function copies count bytes of characters from src to dest. If some regions of the source area and the destination overlap, memmove ensures that the original source bytes in the overlapping region are copied before being overwritten.
Parameters:
dest new buffer
src buffer to copy
count number of bytes to copy
Returns:
the value of dest
Referenced by BufFragGroup< ChainClass, max_frags >::AddFragment(), MediaData< ChainClass, max_frags, local_bufsize >::AddLocalFragment(), and OsclPtr::Append().
OSCL_COND_IMPORT_REF void* oscl_memmove32 (void * dest, const void * src, uint32 count)
Same functionality as oscl_memmove, yet optimized for memory alligned on 32-bit boundary
Parameters:
dest new buffer
src buffer to copy
count number of bytes to copy
Returns:
the value of dest
OSCL_COND_IMPORT_REF void* oscl_memset (void * dest, uint8 val, uint32 count)
Sets the bytes of a buffer to a specified character
Parameters:
dest buffer to modify
val character to set
count number of bytes to set
Returns:
the value of dest
Referenced by OsclMemBasicAllocator::allocate(), OsclMemAllocator::allocate(), BufFragGroup< ChainClass, max_frags >::BufFragGroup(), MediaData< ChainClass, max_frags, local_bufsize >::Clear(), BufFragGroup< ChainClass, max_frags >::Clear(), MM_AllocBlockFence::fill_fence(), MM_AllocInfo::MM_AllocInfo(), MM_AllocNode::MM_AllocNode(), MM_FailInsertParam::MM_FailInsertParam(), MM_Stats_CB::MM_Stats_CB(), MM_Stats_t::MM_Stats_t(), OsclUuid::OsclUuid(), MM_FailInsertParam::reset(), and MM_Stats_t::reset().
OSCL_IMPORT_REF void OsclMemInit (OsclAuditCB & auditCB)
Initialize an OsclAuditCB object. Sets the stats node pointer to null, and sets the audit pointer to the global audit object.
Parameters:
auditCB memory management audit object
Variable Documentation
const uint32 MM_AllocBlockHdr::ALLOC_NODE_FLAG = 0x80000000 [static, inherited]
Referenced by MM_AllocBlockHdr::isAllocNodePtr(), and MM_AllocBlockHdr::setAllocNodeFlag().
OSCL API
Posting Version: CORE_9.005.1.1