oscl: Oscl_Tag< Alloc > Struct Template Reference
Oscl_Tag< Alloc > Struct Template Reference
[OSCL Base]
#include <oscl_tagtree.h>
Public Member Functions
Oscl_Tag (const Oscl_Tag< Alloc > &t)
Oscl_Tag (const tag_base_type &t)
~Oscl_Tag ()
bool operator< (const Oscl_Tag< Alloc > &x) const
Data Fields
Oscl_TAlloc< tag_base_unit, Alloc > tagAllocator
tag_base_type tag
template<class Alloc>
struct Oscl_Tag< Alloc >
Constructor & Destructor Documentation
template<class Alloc> Oscl_Tag< Alloc >::Oscl_Tag (const Oscl_Tag< Alloc > & t) [inline]
References Oscl_Tag< Alloc >::tag, Oscl_Tag_Base::tag_copy(), Oscl_Tag_Base::tag_len(), and Oscl_Tag< Alloc >::tagAllocator.
template<class Alloc> Oscl_Tag< Alloc >::Oscl_Tag (const tag_base_type & t) [inline]
References Oscl_Tag< Alloc >::tag, Oscl_Tag_Base::tag_copy(), Oscl_Tag_Base::tag_len(), and Oscl_Tag< Alloc >::tagAllocator.
template<class Alloc> Oscl_Tag< Alloc >::~Oscl_Tag () [inline]
References Oscl_TAlloc< T, Alloc >::deallocate(), Oscl_Tag< Alloc >::tag, and Oscl_Tag< Alloc >::tagAllocator.
Member Function Documentation
template<class Alloc> bool Oscl_Tag< Alloc >::operator< (const Oscl_Tag< Alloc > & x) const [inline]
References Oscl_Tag< Alloc >::tag, and Oscl_Tag_Base::tag_cmp().
Field Documentation
template<class Alloc> tag_base_type Oscl_Tag< Alloc >::tag
Referenced by Oscl_TagTree< T, Alloc >::Node::depth(), Oscl_TagTree< PVLogger *, alloc_type >::insert(), Oscl_Tag< Alloc >::operator<(), Oscl_Tag< Alloc >::Oscl_Tag(), and Oscl_Tag< Alloc >::~Oscl_Tag().
template<class Alloc> Oscl_TAlloc<tag_base_unit, Alloc> Oscl_Tag< Alloc >::tagAllocator
Referenced by Oscl_Tag< Alloc >::Oscl_Tag(), and Oscl_Tag< Alloc >::~Oscl_Tag().
The documentation for this struct was generated from the following file:
oscl_tagtree.h
OSCL API
Posting Version: CORE_9.005.1.1