oscl: MM_AllocNode Struct Reference
MM_AllocNode Struct Reference
[OSCL Memory]
#include <oscl_mem_audit.h>
Public Member Functions
MM_AllocNode ()
~MM_AllocNode ()
void * operator new (oscl_memsize_t size)
void * operator new (oscl_memsize_t size, MM_AllocNode *ptr)
void operator delete (void *ptr) throw ()
Data Fields
MM_AllocInfo * pAllocInfo
MM_AllocNode * pPrev
MM_AllocNode * pNext
Constructor & Destructor Documentation
MM_AllocNode::MM_AllocNode () [inline]
References oscl_memset().
MM_AllocNode::~MM_AllocNode () [inline]
References OSCL_DELETE, and pAllocInfo.
Member Function Documentation
void MM_AllocNode::operator delete (void * ptr) throw () [inline]
References Oscl_TAlloc< T, Alloc >::deallocate().
void* MM_AllocNode::operator new (oscl_memsize_t size, MM_AllocNode * ptr) [inline]
References OSCL_UNUSED_ARG.
void* MM_AllocNode::operator new (oscl_memsize_t size) [inline]
References Oscl_TAlloc< T, Alloc >::allocate(), and OSCL_UNUSED_ARG.
Field Documentation
MM_AllocInfo* MM_AllocNode::pAllocInfo
Referenced by ~MM_AllocNode().
MM_AllocNode* MM_AllocNode::pNext
MM_AllocNode* MM_AllocNode::pPrev
The documentation for this struct was generated from the following file:
oscl_mem_audit.h
OSCL API
Posting Version: CORE_9.005.1.1