oscl: MM_AllocInfo Struct Reference
MM_AllocInfo Struct Reference
[OSCL Memory]
#include <oscl_mem_audit.h>
Public Member Functions
MM_AllocInfo ()
~MM_AllocInfo ()
void * operator new (oscl_memsize_t size)
void * operator new (oscl_memsize_t size, MM_AllocInfo *ptr)
void operator delete (void *ptr) throw ()
Data Fields
uint32 allocNum
char * pFileName
uint32 lineNo
uint32 size
void * pMemBlock
OsclMemStatsNode * pStatsNode
bool bSetFailure
Constructor & Destructor Documentation
MM_AllocInfo::MM_AllocInfo () [inline]
References oscl_memset().
MM_AllocInfo::~MM_AllocInfo () [inline]
References Oscl_TAlloc< T, Alloc >::deallocate(), and pFileName.
Member Function Documentation
void MM_AllocInfo::operator delete (void * ptr) throw () [inline]
References Oscl_TAlloc< T, Alloc >::deallocate().
void* MM_AllocInfo::operator new (oscl_memsize_t size, MM_AllocInfo * ptr) [inline]
References OSCL_UNUSED_ARG.
void* MM_AllocInfo::operator new (oscl_memsize_t size) [inline]
References Oscl_TAlloc< T, Alloc >::allocate(), and OSCL_UNUSED_ARG.
Field Documentation
uint32 MM_AllocInfo::allocNum
bool MM_AllocInfo::bSetFailure
uint32 MM_AllocInfo::lineNo
char* MM_AllocInfo::pFileName
Referenced by ~MM_AllocInfo().
void* MM_AllocInfo::pMemBlock
OsclMemStatsNode* MM_AllocInfo::pStatsNode
uint32 MM_AllocInfo::size
The documentation for this struct was generated from the following file:
oscl_mem_audit.h
OSCL API
Posting Version: CORE_9.005.1.1