oscl: Oscl_TagTree< T, Alloc >::Node Struct Reference
Oscl_TagTree< T, Alloc >::Node Struct Reference
#include <oscl_tagtree.h>
Public Types
typedef Oscl_Vector< Node
*, Alloc > children_type
Public Member Functions
Node ()
void sort_children ()
tag_type::size_type depth ()
Data Fields
tag_type tag
T value
Node * parent
children_type children
template<class T, class Alloc>
struct Oscl_TagTree< T, Alloc >::Node
Member Typedef Documentation
template<class T, class Alloc> typedef Oscl_Vector<Node*, Alloc> Oscl_TagTree< T, Alloc >::Node::children_type
Constructor & Destructor Documentation
template<class T, class Alloc> Oscl_TagTree< T, Alloc >::Node::Node () [inline]
Member Function Documentation
template<class T, class Alloc> tag_type::size_type Oscl_TagTree< T, Alloc >::Node::depth () [inline]
References Oscl_Tag< Alloc >::tag, Oscl_TagTree< T, Alloc >::Node::tag, and Oscl_Tag_Base::tag_depth().
template<class T, class Alloc> void Oscl_TagTree< T, Alloc >::Node::sort_children () [inline]
References Oscl_Vector< T, Alloc >::begin(), Oscl_TagTree< T, Alloc >::Node::children, Oscl_Vector_Base::empty(), and Oscl_Vector< T, Alloc >::end().
Field Documentation
template<class T, class Alloc> children_type Oscl_TagTree< T, Alloc >::Node::children
Referenced by Oscl_TagTree< T, Alloc >::Node::sort_children().
template<class T, class Alloc> Node* Oscl_TagTree< T, Alloc >::Node::parent
template<class T, class Alloc> tag_type Oscl_TagTree< T, Alloc >::Node::tag
Referenced by Oscl_TagTree< T, Alloc >::Node::depth().
template<class T, class Alloc> T Oscl_TagTree< T, Alloc >::Node::value
The documentation for this struct was generated from the following file:
oscl_tagtree.h
OSCL API
Posting Version: CORE_9.005.1.1