oscl: MM_FailInsertParam Struct Reference
MM_FailInsertParam Struct Reference
[OSCL Memory]
#include <oscl_mem_audit.h>
Public Member Functions
MM_FailInsertParam ()
void reset ()
void * operator new (oscl_memsize_t size)
void * operator new (oscl_memsize_t size, MM_FailInsertParam *ptr)
void operator delete (void *ptr) throw ()
Data Fields
uint32 nAllocNum
uint16 xsubi [3]
Constructor & Destructor Documentation
MM_FailInsertParam::MM_FailInsertParam () [inline]
References oscl_memset(), and xsubi.
Member Function Documentation
void MM_FailInsertParam::operator delete (void * ptr) throw () [inline]
References Oscl_TAlloc< T, Alloc >::deallocate().
void* MM_FailInsertParam::operator new (oscl_memsize_t size, MM_FailInsertParam * ptr) [inline]
References OSCL_UNUSED_ARG.
void* MM_FailInsertParam::operator new (oscl_memsize_t size) [inline]
References Oscl_TAlloc< T, Alloc >::allocate(), and OSCL_UNUSED_ARG.
void MM_FailInsertParam::reset () [inline]
References nAllocNum, oscl_memset(), and xsubi.
Referenced by OsclMemStatsNode::reset().
Field Documentation
uint32 MM_FailInsertParam::nAllocNum
Referenced by reset().
uint16 MM_FailInsertParam::xsubi[3]
Referenced by MM_FailInsertParam(), and reset().
The documentation for this struct was generated from the following file:
oscl_mem_audit.h
OSCL API
Posting Version: CORE_9.005.1.1