oscl: MM_Stats_CB Struct Reference
MM_Stats_CB Struct Reference
[OSCL Memory]
#include <oscl_mem_audit.h>
Public Member Functions
MM_Stats_CB ()
void * operator new (oscl_memsize_t size)
void * operator new (oscl_memsize_t size, MM_Stats_CB *ptr)
void operator delete (void *ptr) throw ()
Data Fields
const char * tag
const MM_Stats_t * pStats
uint32 num_child_nodes
Constructor & Destructor Documentation
MM_Stats_CB::MM_Stats_CB () [inline]
References oscl_memset().
Member Function Documentation
void MM_Stats_CB::operator delete (void * ptr) throw () [inline]
References Oscl_TAlloc< T, Alloc >::deallocate().
void* MM_Stats_CB::operator new (oscl_memsize_t size, MM_Stats_CB * ptr) [inline]
References OSCL_UNUSED_ARG.
void* MM_Stats_CB::operator new (oscl_memsize_t size) [inline]
References Oscl_TAlloc< T, Alloc >::allocate(), and OSCL_UNUSED_ARG.
Field Documentation
uint32 MM_Stats_CB::num_child_nodes
const MM_Stats_t* MM_Stats_CB::pStats
const char* MM_Stats_CB::tag
The documentation for this struct was generated from the following file:
oscl_mem_audit.h
OSCL API
Posting Version: CORE_9.005.1.1