oscl: StrCSumPtrLen Struct Reference
StrCSumPtrLen Struct Reference
[OSCL Util]
same as StrPtrLen, but includes checksum field and method to speed up querying
#include <oscl_str_ptr_len.h>
Public Types
typedef int16 CheckSumType
Public Member Functions
void setPtrLen (const char *newPtr, uint32 newLen)
CheckSumType getCheckSum () const
OSCL_IMPORT_REF void setCheckSum ()
StrCSumPtrLen ()
StrCSumPtrLen (const char *newPtr)
StrCSumPtrLen (const char *newPtr, uint32 newLen)
StrCSumPtrLen (const StrCSumPtrLen &rhs)
StrCSumPtrLen (const StrPtrLen &rhs)
c_bool isCIEquivalentTo (const StrCSumPtrLen &rhs) const
c_bool operator== (const StrCSumPtrLen &rhs) const
c_bool operator!= (const StrCSumPtrLen &rhs) const
StrCSumPtrLen & operator= (const StrCSumPtrLen &rhs)
StrCSumPtrLen & operator= (const StrPtrLen &rhs)
StrCSumPtrLen & operator= (const char *rhs)
Protected Attributes
CheckSumType checkSum
Detailed Description
same as StrPtrLen, but includes checksum field and method to speed up querying
Member Typedef Documentation
typedef int16 StrCSumPtrLen::CheckSumType
Constructor & Destructor Documentation
StrCSumPtrLen::StrCSumPtrLen () [inline]
StrCSumPtrLen::StrCSumPtrLen (const char * newPtr) [inline]
References setCheckSum().
StrCSumPtrLen::StrCSumPtrLen (const char * newPtr, uint32 newLen) [inline]
References setCheckSum().
StrCSumPtrLen::StrCSumPtrLen (const StrCSumPtrLen & rhs) [inline]
StrCSumPtrLen::StrCSumPtrLen (const StrPtrLen & rhs) [inline]
References setCheckSum().
Member Function Documentation
CheckSumType StrCSumPtrLen::getCheckSum () const [inline]
References checkSum.
Referenced by isCIEquivalentTo(), and operator==().
c_bool StrCSumPtrLen::isCIEquivalentTo (const StrCSumPtrLen & rhs) const [inline]
References getCheckSum().
c_bool StrCSumPtrLen::operator!= (const StrCSumPtrLen & rhs) const [inline]
StrCSumPtrLen& StrCSumPtrLen::operator= (const char * rhs) [inline]
Reimplemented from StrPtrLen.
References operator=(), and setCheckSum().
StrCSumPtrLen& StrCSumPtrLen::operator= (const StrPtrLen & rhs) [inline]
Reimplemented from StrPtrLen.
References operator=(), and setCheckSum().
StrCSumPtrLen& StrCSumPtrLen::operator= (const StrCSumPtrLen & rhs) [inline]
References checkSum.
Referenced by operator=().
c_bool StrCSumPtrLen::operator== (const StrCSumPtrLen & rhs) const [inline]
References getCheckSum().
OSCL_IMPORT_REF void StrCSumPtrLen::setCheckSum ()
Referenced by operator=(), setPtrLen(), and StrCSumPtrLen().
void StrCSumPtrLen::setPtrLen (const char * newPtr, uint32 newLen) [inline]
Reimplemented from StrPtrLen.
References setCheckSum().
Field Documentation
CheckSumType StrCSumPtrLen::checkSum [protected]
Referenced by getCheckSum(), and operator=().
The documentation for this struct was generated from the following file:
oscl_str_ptr_len.h
OSCL API
Posting Version: CORE_9.005.1.1