oscl: MM_AllocBlockFence Struct Reference
MM_AllocBlockFence Struct Reference
[OSCL Memory]
#include <oscl_mem_audit_internals.h>
Public Member Functions
MM_AllocBlockFence ()
void fill_fence ()
bool check_fence ()
Data Fields
uint8 pad [COMPUTE_MEM_ALIGN_SIZE(sizeof(MM_AllocBlockHdr), MIN_FENCE_SIZE, MEM_ALIGN_SIZE)]
Constructor & Destructor Documentation
MM_AllocBlockFence::MM_AllocBlockFence () [inline]
References fill_fence().
Member Function Documentation
bool MM_AllocBlockFence::check_fence () [inline]
References FENCE_PATTERN, and pad.
void MM_AllocBlockFence::fill_fence () [inline]
References FENCE_PATTERN, oscl_memset(), and pad.
Referenced by MM_AllocBlockFence().
Field Documentation
uint8 MM_AllocBlockFence::pad[COMPUTE_MEM_ALIGN_SIZE(sizeof(MM_AllocBlockHdr), MIN_FENCE_SIZE, MEM_ALIGN_SIZE)]
Referenced by check_fence(), and fill_fence().
The documentation for this struct was generated from the following file:
oscl_mem_audit_internals.h
OSCL API
Posting Version: CORE_9.005.1.1