oscl: StrPtrLen Struct Reference
StrPtrLen Struct Reference
[OSCL Util]
This data structure encapsulates a set of functions used to perform.
#include <oscl_str_ptr_len.h>
Public Member Functions
StrPtrLen (const char *newPtr)
StrPtrLen (const char *newPtr, uint32 newLen)
StrPtrLen ()
StrPtrLen (const StrPtrLen &rhs)
const char * c_str () const
int32 length () const
int32 size () const
void setPtrLen (const char *newPtr, uint32 newLen)
c_bool isCIEquivalentTo (const StrPtrLen &rhs) const
c_bool isCIPrefixOf (const StrPtrLen &rhs) const
int32 operator== (const StrPtrLen &rhs) const
int32 operator!= (const StrPtrLen &rhs) const
StrPtrLen & operator= (const StrPtrLen &rhs)
StrPtrLen & operator= (const char *rhs)
Protected Member Functions
bool isLetter (const char c) const
Protected Attributes
const char * ptr
int32 len
Detailed Description
This data structure encapsulates a set of functions used to perform.
standard string operations. It should be used for null-terminated constant (non-modifiable) strings of char type.
Constructor & Destructor Documentation
StrPtrLen::StrPtrLen (const char * newPtr) [inline]
References len, and oscl_strlen().
StrPtrLen::StrPtrLen (const char * newPtr, uint32 newLen) [inline]
StrPtrLen::StrPtrLen () [inline]
StrPtrLen::StrPtrLen (const StrPtrLen & rhs) [inline]
Member Function Documentation
const char* StrPtrLen::c_str () const [inline]
References ptr.
c_bool StrPtrLen::isCIEquivalentTo (const StrPtrLen & rhs) const [inline]
References isCIPrefixOf(), and len.
c_bool StrPtrLen::isCIPrefixOf (const StrPtrLen & rhs) const [inline]
References isLetter(), len, OSCL_ASCII_CASE_MAGIC_BIT, and ptr.
Referenced by isCIEquivalentTo().
bool StrPtrLen::isLetter (const char c) const [inline, protected]
Referenced by isCIPrefixOf().
int32 StrPtrLen::length () const [inline]
References len.
int32 StrPtrLen::operator!= (const StrPtrLen & rhs) const [inline]
StrPtrLen& StrPtrLen::operator= (const char * rhs) [inline]
Reimplemented in StrCSumPtrLen.
References len, oscl_strlen(), and ptr.
StrPtrLen& StrPtrLen::operator= (const StrPtrLen & rhs) [inline]
Reimplemented in StrCSumPtrLen.
References len, and ptr.
int32 StrPtrLen::operator== (const StrPtrLen & rhs) const [inline]
References len, oscl_strncmp(), and ptr.
void StrPtrLen::setPtrLen (const char * newPtr, uint32 newLen) [inline]
Reimplemented in StrCSumPtrLen.
References len, and ptr.
int32 StrPtrLen::size () const [inline]
References len.
Field Documentation
int32 StrPtrLen::len [protected]
Referenced by isCIEquivalentTo(), isCIPrefixOf(), length(), operator=(), operator==(), setPtrLen(), size(), and StrPtrLen().
const char* StrPtrLen::ptr [protected]
Referenced by c_str(), isCIPrefixOf(), operator=(), operator==(), and setPtrLen().
The documentation for this struct was generated from the following file:
oscl_str_ptr_len.h
OSCL API
Posting Version: CORE_9.005.1.1