oscl: Oscl_Tag_Base Struct Reference
Oscl_Tag_Base Struct Reference
[OSCL Base]
#include <oscl_tagtree.h>
Public Types
typedef char tag_base_unit
typedef tag_base_unit * tag_base_type
typedef uint32 size_type
Public Member Functions
bool operator() (const tag_base_type &x, const tag_base_type &y) const
size_type tag_len (const tag_base_type &t) const
tag_base_type tag_copy (tag_base_type &dest, const tag_base_type &src) const
int32 tag_cmp (const tag_base_type &x, const tag_base_type &y) const
OSCL_IMPORT_REF tag_base_type tag_ancestor (tag_base_type &dest, const tag_base_type &src) const
OSCL_IMPORT_REF size_type tag_depth (const tag_base_type &t) const
Member Typedef Documentation
typedef uint32 Oscl_Tag_Base::size_type
typedef tag_base_unit* Oscl_Tag_Base::tag_base_type
typedef char Oscl_Tag_Base::tag_base_unit
Member Function Documentation
bool Oscl_Tag_Base::operator() (const tag_base_type & x, const tag_base_type & y) const [inline]
References tag_cmp().
OSCL_IMPORT_REF tag_base_type Oscl_Tag_Base::tag_ancestor (tag_base_type & dest, const tag_base_type & src) const
Referenced by Oscl_TagTree< PVLogger *, alloc_type >::insert().
int32 Oscl_Tag_Base::tag_cmp (const tag_base_type & x, const tag_base_type & y) const [inline]
References oscl_strlen(), and oscl_strncmp().
Referenced by operator()(), and Oscl_Tag< Alloc >::operator<().
tag_base_type Oscl_Tag_Base::tag_copy (tag_base_type & dest, const tag_base_type & src) const [inline]
References oscl_strlen(), and oscl_strncpy().
Referenced by Oscl_Tag< Alloc >::Oscl_Tag().
OSCL_IMPORT_REF size_type Oscl_Tag_Base::tag_depth (const tag_base_type & t) const
Referenced by Oscl_TagTree< T, Alloc >::Node::depth(), and Oscl_TagTree< PVLogger *, alloc_type >::insert().
size_type Oscl_Tag_Base::tag_len (const tag_base_type & t) const [inline]
References oscl_strlen().
Referenced by Oscl_Tag< Alloc >::Oscl_Tag().
The documentation for this struct was generated from the following file:
oscl_tagtree.h
OSCL API
Posting Version: CORE_9.005.1.1